frontend:
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**'

backend:
  - changed-files:
      - any-glob-to-any-file: 'apps/api/**'

database:
  - changed-files:
      - any-glob-to-any-file: 'packages/db/**'

infrastructure:
  - changed-files:
      - any-glob-to-any-file: 'infrastructure/**'

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

types:
  - changed-files:
      - any-glob-to-any-file: 'packages/types/**'

utils:
  - changed-files:
      - any-glob-to-any-file: 'packages/utils/**'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - '**/*.md'
