import type { ArtistSeedConfig } from '../types'
import { cdnUrl, seedKey } from '../cdn'

export const abbeyConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-abbey-peters-cognito',
    email: 'abbey@abbey-peters.com',
    fullName: 'Abbey Peters',
    avatarUrl: cdnUrl(seedKey('abbey-peters', 'profile')),
  },
  profile: {
    displayName: 'Abbey Peters',
    slug: 'abbey-peters',
    bio: 'Abbey Peters is an artist working primarily with ceramics and collected ephemeral materials. She is currently based in Denver, CO and serves as the Phipps Visiting Professor of Ceramics at the University of Denver. She holds an MFA in Ceramics from the University of Iowa and a BFA from the University of Arkansas. Her work has been exhibited across the US and Canada in over forty group exhibitions, in addition to recent solo shows at Berea College and UIHC Project Art. Peters has received international research grants supporting projects on reproductive care, seed preservation, and beekeeping in London, UK. She has completed residencies at laRex l\'Atelier in France, the inaugural CIRCA Exchange, and Vermont Studio Center.',
    location: 'Denver, CO',
    websiteUrl: 'https://abbey-peters.com',
    instagramUrl: 'https://www.instagram.com/abbey_peters',
    originZip: '80210',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('abbey-peters', 'cover')),
    profileImageUrl: cdnUrl(seedKey('abbey-peters', 'profile')),
    applicationSource: 'advisor_network',
    isDemo: false,
  },
  categories: ['ceramics', 'mixed_media'],
  cvEntries: [
    // Education
    { type: 'education', title: 'MFA, Ceramics (Sculpture Secondary)', institution: 'University of Iowa', year: 2024, sortOrder: 1 },
    { type: 'education', title: 'MA, Ceramics', institution: 'University of Iowa', year: 2023, sortOrder: 2 },
    { type: 'education', title: 'BFA, Studio Art (Minor: Art History)', institution: 'University of Arkansas', year: 2019, sortOrder: 3 },
    // Solo Exhibitions
    { type: 'exhibition', title: 'Carefully Held', institution: 'Berea College, Berea, KY', year: 2025, sortOrder: 4 },
    { type: 'exhibition', title: '24: Sub Rosa', institution: 'UI Health Care: Project Art, Iowa City, IA', year: 2024, sortOrder: 5 },
    { type: 'exhibition', title: 'From Lemons to Leaves', institution: 'Drewelowe Gallery, Iowa City, IA', year: 2024, sortOrder: 6 },
    // Selected Group Exhibitions
    { type: 'exhibition', title: 'Beyond the Garden (NCECA 2026)', institution: 'Detroit, MI', year: 2026, sortOrder: 7 },
    { type: 'exhibition', title: 'What Holds', institution: 'Vessels + Sticks, Toronto, Canada', year: 2025, sortOrder: 8 },
    { type: 'exhibition', title: 'Soft Power', institution: 'Lydia and Robert Ruyle Gallery, University of Northern Colorado, Greeley, CO', year: 2025, sortOrder: 9 },
    { type: 'exhibition', title: 'Small Favors', institution: 'The Clay Studio, Philadelphia, PA', year: 2024, sortOrder: 10 },
    { type: 'exhibition', title: 'NCECA Juried Student Exhibition', institution: 'Visual Art Center, Richmond, VA', year: 2024, sortOrder: 11 },
    // Residencies
    { type: 'residency', title: 'Artist in Residence, Ceramics', institution: 'University of Denver, Denver, CO', year: 2026, sortOrder: 12 },
    { type: 'residency', title: 'Artist in Residence, Sculpture', institution: 'Vermont Studio Center, Johnson, VT', year: 2025, sortOrder: 13 },
    { type: 'residency', title: 'International Artist Residency Exchange', institution: "laRex l'Atelier, St. Raphael, France", year: 2023, sortOrder: 14 },
    // Awards
    { type: 'award', title: 'Vermont Studio Center Full Fellowship', institution: 'Vermont Studio Center, Johnson, VT', year: 2025, sortOrder: 15 },
    { type: 'award', title: 'Athena Fund Finalist', institution: 'Arc Gallery, Chicago, IL', year: 2024, sortOrder: 16 },
    { type: 'award', title: 'CIRCA Residency Exchange Grant', institution: 'Boulder, CO', year: 2023, sortOrder: 17 },
    // Press
    { type: 'press', title: 'Artist Feature', institution: 'Suboart Magazine, Portugal', year: 2026, sortOrder: 18 },
    { type: 'press', title: 'Spotlight: A Decorative Vessel', institution: 'Ceramics Monthly', year: 2025, sortOrder: 19 },
  ],
  listings: [
    // Available listings (5 selected from her 21)
    {
      title: 'Drippy Teal Box',
      description: 'Functional lidded box made with stoneware and glaze.',
      medium: 'stoneware',
      category: 'ceramics',
      price: 11500,
      status: 'available',
      isDocumented: true,
      artworkLength: 4.5, artworkWidth: 5.5, artworkHeight: 4,
      packedLength: 8.5, packedWidth: 9.5, packedHeight: 8,
      packedWeight: 3,
    },
    {
      title: 'Purple and Lighter Purple Box',
      description: 'Functional lidded box made with stoneware and glaze.',
      medium: 'stoneware',
      category: 'ceramics',
      price: 12500,
      status: 'available',
      isDocumented: false,
      artworkLength: 6, artworkWidth: 5, artworkHeight: 3.5,
      packedLength: 10, packedWidth: 9, packedHeight: 7.5,
      packedWeight: 3.5,
    },
    {
      title: 'Pink Candlestick with Hidden Base',
      description: 'Functional candlestick with a hidden compartment, made with stoneware and glaze.',
      medium: 'stoneware',
      category: 'ceramics',
      price: 6000,
      status: 'available',
      isDocumented: false,
      artworkLength: 5.5, artworkWidth: 5.5, artworkHeight: 5,
      packedLength: 9.5, packedWidth: 9.5, packedHeight: 9,
      packedWeight: 2.5,
    },
    {
      title: 'White with Tea Bag Box',
      description: 'Functional lidded box with embedded tea bag detail, made with stoneware and glaze.',
      medium: 'stoneware',
      category: 'ceramics',
      price: 15000,
      status: 'available',
      isDocumented: true,
      artworkLength: 5, artworkWidth: 5, artworkHeight: 7,
      packedLength: 9, packedWidth: 9, packedHeight: 11,
      packedWeight: 4,
    },
    {
      title: 'Pink Vase',
      description: 'Handmade vase in stoneware and glaze.',
      medium: 'stoneware',
      category: 'ceramics',
      price: 5500,
      status: 'available',
      isDocumented: false,
      artworkLength: 4, artworkWidth: 4, artworkHeight: 7,
      packedLength: 8, packedWidth: 8, packedHeight: 11,
      packedWeight: 2.5,
    },
    // Sold listings (2 for archive)
    {
      title: 'Teal Vase',
      description: 'Handmade vase in stoneware and glaze.',
      medium: 'stoneware',
      category: 'ceramics',
      price: 5500,
      status: 'sold',
      isDocumented: false,
      artworkLength: 5, artworkWidth: 5, artworkHeight: 6.5,
      packedLength: 9, packedWidth: 9, packedHeight: 10.5,
      packedWeight: 3,
    },
    {
      title: 'Pale Pink Box with Key',
      description: 'Functional lidded box with embedded key detail, made with stoneware and glaze.',
      medium: 'stoneware',
      category: 'ceramics',
      price: 12500,
      status: 'sold',
      isDocumented: true,
      artworkLength: 7, artworkWidth: 6, artworkHeight: 5.5,
      packedLength: 11, packedWidth: 10, packedHeight: 9.5,
      packedWeight: 4.5,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('abbey-peters', 'process/studio')), sortOrder: 0 },
    { type: 'photo', url: cdnUrl(seedKey('abbey-peters', 'process/kiln')), sortOrder: 1 },
  ],
}
