import type { ArtistSeedConfig } from '../types'
import { cdnUrl, seedKey } from '../cdn'

export const davidConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-david-morrison-cognito',
    email: 'davidmorrison167@gmail.com',
    fullName: 'David Morrison',
    avatarUrl: cdnUrl(seedKey('david-morrison', 'profile')),
  },
  profile: {
    displayName: 'David Morrison',
    slug: 'david-morrison',
    bio: 'David was born and raised in Batavia, IL a western suburb of Chicago. He attended St. Olaf College where he received his B.A. in studio art and a concentration in Asian Studies. Upon graduating he was an artistic intern for the summer and fall of 2019 at Anderson Ranch Arts Center. He is a ceramic oriented mixed media artist and earned his MFA in Art from the University of Oklahoma. He is making playful objects exploring the Anthropocene through re-contextualizing the superfluous waste from our consumption within ceramic assemblages. He is working and pursuing his studio practice in Winooski, Vermont.',
    location: 'Winooski, VT',
    websiteUrl: 'https://morrison-david.com',
    instagramUrl: 'https://www.instagram.com/david_morrison_ceramics',
    originZip: '05404',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('david-morrison', 'cover')),
    profileImageUrl: cdnUrl(seedKey('david-morrison', 'profile')),
    applicationSource: 'advisor_network',
    isDemo: false,
  },
  categories: ['ceramics', 'mixed_media'],
  cvEntries: [
    // Education
    { type: 'education', title: 'MFA, Art', institution: 'University of Oklahoma', year: 2025, sortOrder: 1 },
    { type: 'education', title: 'BA, Studio Art (concentration: Asian Studies)', institution: 'St. Olaf College, Northfield, MN', year: 2019, sortOrder: 2 },
    // Residencies
    { type: 'residency', title: 'Artist in Residence', institution: 'Vermont Studio Center, Johnson, VT', year: 2025, sortOrder: 3 },
    // Exhibitions
    { type: 'exhibition', title: '63rd Faenza Prize (Shortlisted)', institution: 'International Museum of Ceramics, Faenza, Italy', year: 2025, sortOrder: 4 },
    { type: 'exhibition', title: 'NCECA National Student Juried Exhibition', institution: 'Richmond, VA', year: 2024, sortOrder: 5 },
    { type: 'exhibition', title: 'Hot, Happy Mess — The Dysfunction of Process', institution: 'The Guild, Northfield, MN', year: 2020, sortOrder: 6 },
    { type: 'exhibition', title: 'Interim', institution: 'Patton-Malott Gallery, Anderson Ranch, Snowmass Village, CO', year: 2019, sortOrder: 7 },
    { type: 'exhibition', title: 'Cross River Connections (NCECA)', institution: 'The Phipps, Hudson, WI', year: 2019, sortOrder: 8 },
    // Awards
    { type: 'award', title: 'Scholarship', institution: 'Anderson Ranch Arts Center, Snowmass Village, CO', year: 2018, sortOrder: 9 },
  ],
  listings: [
    // Available listings
    {
      title: 'micro-landscape (0011)',
      description: 'Porcelaneous stoneware sculptural landscape with glaze, neon, electricity, and silicon.',
      medium: 'porcelaneous stoneware, glaze, neon, electricity, silicon',
      category: 'ceramics',
      price: 55000,
      status: 'available',
      isDocumented: true,
      artworkLength: 11, artworkWidth: 8, artworkHeight: 8,
      packedLength: 15, packedWidth: 12, packedHeight: 12,
      packedWeight: 8,
    },
    {
      title: 'Core Sample Cup (27)',
      description: 'Functional cup from the Core Sample series. Earthenware with mixed media.',
      medium: 'earthenware, mixed media',
      category: 'ceramics',
      price: 5500,
      status: 'available',
      isDocumented: false,
      artworkLength: 4, artworkWidth: 3.5, artworkHeight: 4,
      packedLength: 8, packedWidth: 7.5, packedHeight: 8,
      packedWeight: 2,
    },
    {
      title: 'Core Sample Mug (22)',
      description: 'Functional mug from the Core Sample series. Earthenware with mixed media.',
      medium: 'earthenware, mixed media',
      category: 'ceramics',
      price: 5500,
      status: 'available',
      isDocumented: false,
      artworkLength: 5, artworkWidth: 3.5, artworkHeight: 4.5,
      packedLength: 9, packedWidth: 7.5, packedHeight: 8.5,
      packedWeight: 2,
    },
    {
      title: 'Core Sample Tumbler (14)',
      description: 'Functional tumbler from the Core Sample series. Earthenware with mixed media.',
      medium: 'earthenware, mixed media',
      category: 'ceramics',
      price: 5500,
      status: 'available',
      isDocumented: false,
      artworkLength: 3.5, artworkWidth: 3.5, artworkHeight: 5,
      packedLength: 7.5, packedWidth: 7.5, packedHeight: 9,
      packedWeight: 2,
    },
    // Sold listings
    {
      title: 'Core Sample Mug (29)',
      description: 'Functional mug from the Core Sample series. Earthenware with mixed media.',
      medium: 'earthenware, mixed media',
      category: 'ceramics',
      price: 5500,
      status: 'sold',
      isDocumented: false,
      artworkLength: 5, artworkWidth: 3.5, artworkHeight: 4.5,
      packedLength: 9, packedWidth: 7.5, packedHeight: 8.5,
      packedWeight: 2,
    },
    {
      title: 'Core Sample Bowl (24)',
      description: 'Functional bowl from the Core Sample series. Earthenware with mixed media.',
      medium: 'earthenware, mixed media',
      category: 'ceramics',
      price: 5500,
      status: 'sold',
      isDocumented: false,
      artworkLength: 6, artworkWidth: 6, artworkHeight: 3,
      packedLength: 10, packedWidth: 10, packedHeight: 7,
      packedWeight: 2.5,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('david-morrison', 'process/studio')), sortOrder: 0 },
  ],
}
