// Enums and enum types
export {
  UserRole,
  type UserRoleType,
  ArtistStatus,
  type ArtistStatusType,
  ListingStatus,
  type ListingStatusType,
  ListingType,
  type ListingTypeType,
  Category,
  type CategoryType,
  CommissionStatus,
  type CommissionStatusType,
  OrderStatus,
  type OrderStatusType,
  CvEntryType,
  type CvEntryTypeType,
  ProcessMediaType,
  type ProcessMediaTypeType,
} from './enums'

// Entity interfaces
export type {
  User,
  UserRole as UserRoleRecord,
  ArtistProfile,
  ArtistCategory,
  ArtistCvEntry,
  ArtistProcessMedia,
  Listing,
  ListingImage,
  Commission,
  CommissionUpdate,
  Order,
  Review,
  Save,
  Follow,
  Waitlist,
  // API response types
  ListingWithImages,
  ArtistProfileResponse,
  ArtistSummary,
  ArtistSummaryWithCategories,
  CategoryWithCount,
  ListingListItem,
  ListingDetailResponse,
  PaginatedResponse,
  ApiError,
} from './interfaces'
