// Enums and enum types
export {
  UserRole,
  type UserRoleType,
  ArtistStatus,
  type ArtistStatusType,
  ListingStatus,
  type ListingStatusType,
  ListingType,
  type ListingTypeType,
  Category,
  type CategoryType,
  CommissionStatus,
  type CommissionStatusType,
  OrderStatus,
  type OrderStatusType,
  CvEntryType,
  type CvEntryTypeType,
  ProcessMediaType,
  type ProcessMediaTypeType,
  ApplicationStatus,
  type ApplicationStatusType,
} from './enums'

// Entity interfaces
export type {
  User,
  UserRole as UserRoleRecord,
  ArtistProfile,
  ArtistCategory,
  ArtistCvEntry,
  ArtistProcessMedia,
  Listing,
  ListingImage,
  Commission,
  CommissionUpdate,
  Order,
  Review,
  Save,
  Follow,
  Waitlist,
  // API response types
  ListingWithImages,
  ArtistProfileResponse,
  ArtistSummary,
  ArtistSummaryWithCategories,
  FeaturedArtistItem,
  CategoryWithCount,
  ListingListItem,
  ListingDetailResponse,
  PaginatedResponse,
  ApiError,
  ArtistApplication,
  ApplicationSubmitResponse,
  PresignedPostResponse,
} from './interfaces'

// Validation schemas
export {
  slugParam,
  uuidParam,
  paginationQuery,
  artistsQuery,
  listingsQuery,
  waitlistBody,
  artistSlugParam,
  listingIdParam,
  sanitizeText,
  artistApplicationBody,
  checkEmailQuery,
  presignedUrlBody,
  type ArtistsQuery,
  type ListingsQuery,
  type WaitlistBody,
  type ArtistApplicationBody,
  type CheckEmailQuery,
  type PresignedUrlBody,
} from './schemas'
