import type { ArtistSeedConfig } from '../types'
import { cdnUrl, seedKey } from '../cdn'

// ============================================================================
// Fatima Al-Rashid — Dearborn, MI — fibers, mixed_media — Emerging (30s)
// ============================================================================

const fatimaConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-fatima-al-rashid-cognito',
    email: 'fatima@fatimaalrashidart.com',
    fullName: 'Fatima Al-Rashid',
    avatarUrl: cdnUrl(seedKey('fatima-al-rashid', 'profile')),
  },
  profile: {
    displayName: 'Fatima Al-Rashid',
    slug: 'fatima-al-rashid',
    bio: 'Fatima Al-Rashid is a Lebanese-American fiber artist and mixed media maker based in Dearborn, Michigan. Her hand-woven textiles and sculptural installations draw from the rich textile traditions of the Levant — kilim weaving, silk embroidery, and the geometric patterns of Islamic architecture. Al-Rashid weaves on a floor loom using hand-dyed cotton and wool, creating wall hangings and functional textiles that bridge her family\'s heritage with her Midwestern surroundings. She holds an MFA from Cranbrook Academy of Art and a BA from the University of Michigan. Her work has been exhibited at the Arab American National Museum, the Detroit Institute of Arts, and the Textile Society of America conference.',
    location: 'Dearborn, MI',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '48124',
    status: 'approved',
    commissionsOpen: true,
    coverImageUrl: cdnUrl(seedKey('fatima-al-rashid', 'cover')),
    profileImageUrl: cdnUrl(seedKey('fatima-al-rashid', 'profile')),
    applicationSource: 'direct_application',
    isDemo: true,
  },
  categories: ['fibers', 'mixed_media'],
  cvEntries: [
    { type: 'education', title: 'MFA, Fiber', institution: 'Cranbrook Academy of Art, Bloomfield Hills, MI', year: 2021, sortOrder: 1 },
    { type: 'education', title: 'BA, Art and Design', institution: 'University of Michigan, Ann Arbor, MI', year: 2017, sortOrder: 2 },
    { type: 'exhibition', title: 'Woven Worlds', institution: 'Arab American National Museum, Dearborn, MI', year: 2025, sortOrder: 3 },
    { type: 'exhibition', title: 'Material Connections', institution: 'Detroit Institute of Arts, Detroit, MI', year: 2023, sortOrder: 4 },
    { type: 'residency', title: 'Textile Fellow', institution: 'Penland School of Craft, Bakersville, NC', year: 2022, sortOrder: 5 },
    { type: 'award', title: 'Kresge Artist Fellowship', institution: 'Kresge Foundation, Troy, MI', year: 2024, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Beirut Grid',
      description: 'Large hand-woven wall hanging in hand-dyed cotton and wool. The geometric pattern is derived from the tile floors of the artist\'s grandparents\' apartment in Beirut, translated into a woven grid of warm ochre, deep indigo, and natural white. Woven on a four-harness floor loom.',
      medium: 'hand-woven cotton and wool, natural dyes',
      category: 'fibers',
      price: 32000,
      status: 'available',
      isDocumented: true,
      artworkLength: 36, artworkWidth: 48, artworkHeight: 1,
      packedLength: 14, packedWidth: 14, packedHeight: 8,
      packedWeight: 6,
    },
    {
      title: 'Cedar and Sage Scarf',
      description: 'Hand-woven scarf in fine merino wool dyed with cedar bark and sage. The natural dye colors — warm brown and soft green — evoke the landscapes of both Michigan and Lebanon. Lightweight and soft with a plain weave structure.',
      medium: 'hand-woven merino wool, natural dyes',
      category: 'fibers',
      price: 8500,
      status: 'available',
      isDocumented: false,
      artworkLength: 72, artworkWidth: 12, artworkHeight: 0.25,
      packedLength: 12, packedWidth: 8, packedHeight: 4,
      packedWeight: 0.5,
    },
    {
      title: 'Window Fragment',
      description: 'Mixed media piece combining hand-woven cotton strips with plaster fragments and copper wire. The composition references the mashrabiya latticed windows of Levantine architecture. The textile elements are woven in a fine tabby structure with metallic threads.',
      medium: 'hand-woven cotton, plaster, copper wire',
      category: 'mixed_media',
      price: 22000,
      status: 'available',
      isDocumented: true,
      artworkLength: 24, artworkWidth: 18, artworkHeight: 3,
      packedLength: 28, packedWidth: 22, packedHeight: 7,
      packedWeight: 5,
    },
    {
      title: 'Table Runner, Pomegranate',
      description: 'Hand-woven table runner in cotton dyed with pomegranate rinds, producing a warm golden-yellow. The weft pattern creates a subtle diamond motif inspired by traditional Lebanese kilim weaving. Functional and machine washable on gentle cycle.',
      medium: 'hand-woven cotton, pomegranate dye',
      category: 'fibers',
      price: 12000,
      status: 'available',
      isDocumented: false,
      artworkLength: 54, artworkWidth: 14, artworkHeight: 0.25,
      packedLength: 14, packedWidth: 10, packedHeight: 4,
      packedWeight: 1,
    },
    {
      title: 'Levantine Blue',
      description: 'Large wall hanging in hand-dyed indigo cotton and natural white wool. The design abstracts the geometric patterns of Islamic tile work into a bold, contemporary composition. The deep indigo is achieved through multiple dye baths in a natural fermentation vat.',
      medium: 'hand-woven cotton and wool, natural indigo',
      category: 'fibers',
      price: 35000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 40, artworkWidth: 56, artworkHeight: 1,
      packedLength: 14, packedWidth: 14, packedHeight: 10,
      packedWeight: 7,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('fatima-al-rashid', 'process/studio')), sortOrder: 0 },
  ],
}

// ============================================================================
// Yolanda Trevino — San Antonio, TX — fibers, illustration — Mid-career (50s)
// ============================================================================

const yolandaConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-yolanda-trevino-cognito',
    email: 'yolanda@yolandatrevinoart.com',
    fullName: 'Yolanda Trevino',
    avatarUrl: cdnUrl(seedKey('yolanda-trevino', 'profile')),
  },
  profile: {
    displayName: 'Yolanda Trevino',
    slug: 'yolanda-trevino',
    bio: 'Yolanda Trevino is a Tejana fiber artist and illustrator based in San Antonio, Texas. Her hand-embroidered textiles and narrative drawings celebrate the visual culture of the Texas-Mexico border — from the bright papel picado and lotería cards of San Antonio\'s West Side to the botanical landscape of the Hill Country. Trevino learned embroidery from her abuela and has spent over two decades developing her own vocabulary of stitches and motifs. She holds an MFA from the University of Texas at San Antonio and a BFA from Texas State University. Her work has been exhibited at the McNay Art Museum, the Blanton Museum of Art, and Artpace San Antonio. She teaches community embroidery workshops at the Esperanza Peace and Justice Center.',
    location: 'San Antonio, TX',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '78205',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('yolanda-trevino', 'cover')),
    profileImageUrl: cdnUrl(seedKey('yolanda-trevino', 'profile')),
    applicationSource: 'advisor_network',
    isDemo: true,
  },
  categories: ['fibers', 'illustration'],
  cvEntries: [
    { type: 'education', title: 'MFA, Art', institution: 'University of Texas at San Antonio, TX', year: 2005, sortOrder: 1 },
    { type: 'education', title: 'BFA, Studio Art', institution: 'Texas State University, San Marcos, TX', year: 2000, sortOrder: 2 },
    { type: 'exhibition', title: 'Puntadas y Cuentos', institution: 'McNay Art Museum, San Antonio, TX', year: 2025, sortOrder: 3 },
    { type: 'exhibition', title: 'Textile Narratives', institution: 'Blanton Museum of Art, Austin, TX', year: 2022, sortOrder: 4 },
    { type: 'residency', title: 'International Artist Residency', institution: 'Artpace San Antonio, TX', year: 2018, sortOrder: 5 },
    { type: 'award', title: 'Texas Commission on the Arts Individual Artist Grant', institution: 'Austin, TX', year: 2023, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Lotería: La Luna',
      description: 'Hand-embroidered linen depicting a reinterpretation of the La Luna lotería card. Dense satin stitch in midnight blue, silver metallic thread, and pale yellow create a luminous moon over a San Antonio skyline. Mounted on wooden stretcher bars. Over sixty hours of hand stitching.',
      medium: 'hand-embroidered linen, metallic thread',
      category: 'fibers',
      price: 28000,
      status: 'available',
      isDocumented: true,
      artworkLength: 18, artworkWidth: 24, artworkHeight: 1,
      packedLength: 22, packedWidth: 28, packedHeight: 5,
      packedWeight: 3,
    },
    {
      title: 'Papel Picado Study, ink',
      description: 'Original ink illustration of a papel picado banner designed for Día de los Muertos. The intricate cut-paper patterns are rendered in fine-line ink with washes of magenta, orange, and purple watercolor. Drawn from memory of the artist\'s grandmother\'s kitchen.',
      medium: 'ink and watercolor on paper',
      category: 'illustration',
      price: 8500,
      status: 'available',
      isDocumented: false,
      artworkLength: 11, artworkWidth: 14, artworkHeight: 0,
      packedLength: 15, packedWidth: 18, packedHeight: 2,
      packedWeight: 0.5,
    },
    {
      title: 'Hill Country Wildflowers',
      description: 'Embroidered linen sampler of Texas Hill Country wildflowers — bluebonnets, Indian paintbrush, and evening primrose. Each flower is rendered in long and short stitch with hand-dyed cotton floss. A contemporary take on the Victorian botanical sampler tradition.',
      medium: 'hand-embroidered linen, cotton floss',
      category: 'fibers',
      price: 16000,
      status: 'available',
      isDocumented: true,
      artworkLength: 14, artworkWidth: 18, artworkHeight: 1,
      packedLength: 18, packedWidth: 22, packedHeight: 5,
      packedWeight: 2,
    },
    {
      title: 'Embroidered Pillow, Rose',
      description: 'Linen throw pillow with hand-embroidered Castilian rose motif. The design references traditional Mexican Otomí embroidery translated into a muted palette of dusty rose, sage green, and cream. Backed with natural linen and filled with kapok.',
      medium: 'hand-embroidered linen, kapok fill',
      category: 'fibers',
      price: 9500,
      status: 'available',
      isDocumented: false,
      artworkLength: 18, artworkWidth: 18, artworkHeight: 5,
      packedLength: 22, packedWidth: 22, packedHeight: 9,
      packedWeight: 2,
    },
    {
      title: 'Lotería: El Corazón',
      description: 'Hand-embroidered textile depicting the El Corazón lotería card. Crimson and gold thread on natural linen, with the anatomical heart surrounded by flowers and thorns. The most labor-intensive piece in the Lotería series at over eighty hours of stitching.',
      medium: 'hand-embroidered linen, metallic thread',
      category: 'fibers',
      price: 32000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 20, artworkWidth: 26, artworkHeight: 1,
      packedLength: 24, packedWidth: 30, packedHeight: 5,
      packedWeight: 3,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('yolanda-trevino', 'process/studio')), sortOrder: 0 },
  ],
}

// ============================================================================
// Keiko Watanabe — Honolulu, HI — fibers, ceramics — Mid-career (40s)
// ============================================================================

const keikoConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-keiko-watanabe-cognito',
    email: 'keiko@keikowatanabeart.com',
    fullName: 'Keiko Watanabe',
    avatarUrl: cdnUrl(seedKey('keiko-watanabe', 'profile')),
  },
  profile: {
    displayName: 'Keiko Watanabe',
    slug: 'keiko-watanabe',
    bio: 'Keiko Watanabe is a Japanese-American fiber artist and ceramicist based in Honolulu, Hawai\'i. Her work draws from the intersection of Japanese textile arts — shibori, sashiko, and natural indigo dyeing — and the material culture of the Hawaiian Islands. Watanabe creates hand-dyed indigo textiles and raku-fired ceramic vessels, finding formal and conceptual connections between the two practices. The unpredictable results of indigo vat dyeing and raku firing share a surrender to process that is central to her work. She holds an MFA from the University of Hawai\'i at Mānoa and a BFA from the School of the Art Institute of Chicago. Her work has been exhibited at the Honolulu Museum of Art, the Japanese American National Museum, and the Textile Center Minneapolis.',
    location: 'Honolulu, HI',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '96813',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('keiko-watanabe', 'cover')),
    profileImageUrl: cdnUrl(seedKey('keiko-watanabe', 'profile')),
    applicationSource: 'advisor_network',
    isDemo: true,
  },
  categories: ['fibers', 'ceramics'],
  cvEntries: [
    { type: 'education', title: 'MFA, Art', institution: 'University of Hawai\'i at Mānoa, Honolulu, HI', year: 2010, sortOrder: 1 },
    { type: 'education', title: 'BFA, Fiber and Material Studies', institution: 'School of the Art Institute of Chicago, IL', year: 2005, sortOrder: 2 },
    { type: 'exhibition', title: 'Ai and Fire', institution: 'Honolulu Museum of Art, Honolulu, HI', year: 2025, sortOrder: 3 },
    { type: 'exhibition', title: 'Threads of Tradition', institution: 'Japanese American National Museum, Los Angeles, CA', year: 2022, sortOrder: 4 },
    { type: 'residency', title: 'Artist in Residence', institution: 'Haystack Mountain School of Crafts, Deer Isle, ME', year: 2017, sortOrder: 5 },
    { type: 'award', title: 'Hawai\'i State Foundation on Culture and the Arts Fellowship', institution: 'Honolulu, HI', year: 2023, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Shibori Wall Panel, Indigo',
      description: 'Large shibori-dyed wall panel in natural indigo on cotton. The arashi (pole-wrapping) technique creates diagonal stripe patterns that evoke ocean waves. Dyed in the artist\'s own indigo vat cultivated from Okinawan indigo plants. Mounted on a bamboo hanging rod.',
      medium: 'shibori-dyed cotton, natural indigo',
      category: 'fibers',
      price: 28000,
      status: 'available',
      isDocumented: true,
      artworkLength: 36, artworkWidth: 54, artworkHeight: 0.5,
      packedLength: 14, packedWidth: 14, packedHeight: 6,
      packedWeight: 3,
    },
    {
      title: 'Raku Tea Bowl, Copper',
      description: 'Hand-thrown raku-fired tea bowl with a copper matte glaze. The raku firing process — removing the bowl from the kiln at peak temperature and reducing it in combustible material — creates unpredictable metallic lusters and crackling. Each bowl is a unique result of the firing.',
      medium: 'raku-fired stoneware, copper glaze',
      category: 'ceramics',
      price: 12000,
      status: 'available',
      isDocumented: true,
      artworkLength: 5, artworkWidth: 5, artworkHeight: 3.5,
      packedLength: 9, packedWidth: 9, packedHeight: 7.5,
      packedWeight: 2,
    },
    {
      title: 'Sashiko Coasters, Set of Six',
      description: 'Set of six hand-stitched sashiko coasters on indigo-dyed cotton. Each coaster features a different traditional sashiko pattern — hemp leaf, ocean waves, chrysanthemum, tortoiseshell, arrow feather, and linked circles. White cotton thread on deep indigo cloth.',
      medium: 'indigo-dyed cotton, sashiko stitching',
      category: 'fibers',
      price: 6500,
      status: 'available',
      isDocumented: false,
      artworkLength: 4, artworkWidth: 4, artworkHeight: 0.25,
      packedLength: 8, packedWidth: 8, packedHeight: 4.25,
      packedWeight: 0.5,
    },
    {
      title: 'Indigo Scarf, Itajime',
      description: 'Silk scarf dyed with natural indigo using the itajime (shaped-resist) technique. Geometric patterns emerge from folding and clamping the silk between wooden blocks before dyeing. The result is a precise, symmetrical pattern in gradations of blue.',
      medium: 'silk, natural indigo, itajime shibori',
      category: 'fibers',
      price: 14000,
      status: 'available',
      isDocumented: false,
      artworkLength: 72, artworkWidth: 14, artworkHeight: 0.1,
      packedLength: 10, packedWidth: 8, packedHeight: 4,
      packedWeight: 0.5,
    },
    {
      title: 'Raku Vessel, Moon',
      description: 'Tall hand-built raku vessel with a white crackle glaze over a dark clay body. The carbon trapped in the glaze crackle creates dark lines on the white surface, evoking the surface of the moon. Not watertight — intended as a sculptural object.',
      medium: 'raku-fired stoneware, white crackle glaze',
      category: 'ceramics',
      price: 18000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 6, artworkWidth: 6, artworkHeight: 12,
      packedLength: 10, packedWidth: 10, packedHeight: 16,
      packedWeight: 4,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('keiko-watanabe', 'process/studio')), sortOrder: 0 },
  ],
}

export const fibersArtists: ArtistSeedConfig[] = [
  fatimaConfig,
  yolandaConfig,
  keikoConfig,
]
