import type { ArtistSeedConfig } from '../types'
import { cdnUrl, seedKey } from '../cdn'

// ============================================================================
// Maya Chen — Los Angeles, CA — illustration, mixed_media — Emerging (20s)
// ============================================================================

const mayaConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-maya-chen-cognito',
    email: 'maya@mayachenart.com',
    fullName: 'Maya Chen',
    avatarUrl: cdnUrl(seedKey('maya-chen', 'profile')),
  },
  profile: {
    displayName: 'Maya Chen',
    slug: 'maya-chen',
    bio: 'Maya Chen is a Chinese-American illustrator and mixed media artist based in Los Angeles. Her work blends ink drawing, watercolor, and digital collage to create narrative illustrations that explore the immigrant experience, intergenerational memory, and the mythology of everyday objects. Chen graduated from ArtCenter College of Design with a BFA in Illustration and holds an MFA from UCLA. She has exhibited at the Chinese American Museum, the Hammer Museum, and Giant Robot gallery. Her illustrations have been commissioned by the New York Times, McSweeney\'s, and the Asian American Writers\' Workshop. She teaches illustration at Otis College of Art and Design.',
    location: 'Los Angeles, CA',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '90013',
    status: 'approved',
    commissionsOpen: true,
    coverImageUrl: cdnUrl(seedKey('maya-chen', 'cover')),
    profileImageUrl: cdnUrl(seedKey('maya-chen', 'profile')),
    applicationSource: 'direct_application',
    isDemo: true,
  },
  categories: ['illustration', 'mixed_media'],
  cvEntries: [
    { type: 'education', title: 'MFA, Art', institution: 'UCLA, Los Angeles, CA', year: 2023, sortOrder: 1 },
    { type: 'education', title: 'BFA, Illustration', institution: 'ArtCenter College of Design, Pasadena, CA', year: 2019, sortOrder: 2 },
    { type: 'exhibition', title: 'Roots and Routes', institution: 'Chinese American Museum, Los Angeles, CA', year: 2025, sortOrder: 3 },
    { type: 'exhibition', title: 'Made in LA Biennial', institution: 'Hammer Museum, Los Angeles, CA', year: 2023, sortOrder: 4 },
    { type: 'award', title: 'AIGA 50', institution: 'American Institute of Graphic Arts', year: 2024, sortOrder: 5 },
  ],
  listings: [
    {
      title: 'Kitchen Gods',
      description: 'Original ink and watercolor illustration depicting the Zao Jun (kitchen god) shrine in a contemporary Chinese-American kitchen, surrounded by takeout containers, rice cookers, and family photographs. The piece negotiates between traditional mythology and diasporic domesticity.',
      medium: 'ink and watercolor on paper',
      category: 'illustration',
      price: 18000,
      status: 'available',
      isDocumented: true,
      artworkLength: 14, artworkWidth: 18, artworkHeight: 0,
      packedLength: 18, packedWidth: 22, packedHeight: 3,
      packedWeight: 1,
    },
    {
      title: 'Chinatown Grocery No. 4',
      description: 'Detailed pen and ink illustration of a Chinatown grocery storefront with hand-lettered Chinese signage. Part of an ongoing series documenting disappearing small businesses in San Gabriel Valley. Archival pigment print on cotton rag paper, signed.',
      medium: 'archival pigment print, edition of 25',
      category: 'illustration',
      price: 6500,
      status: 'available',
      isDocumented: false,
      artworkLength: 11, artworkWidth: 14, artworkHeight: 0,
      packedLength: 15, packedWidth: 18, packedHeight: 2,
      packedWeight: 0.5,
    },
    {
      title: 'Moon Festival',
      description: 'Mixed media collage combining ink illustration with vintage Chinese newspaper clippings and hand-painted mooncake wrappers. The layers create a palimpsest of cultural memory and seasonal celebration. Mounted on cradled panel.',
      medium: 'ink, watercolor, collage on panel',
      category: 'mixed_media',
      price: 22000,
      status: 'available',
      isDocumented: true,
      artworkLength: 16, artworkWidth: 20, artworkHeight: 1.5,
      packedLength: 20, packedWidth: 24, packedHeight: 5,
      packedWeight: 4,
    },
    {
      title: 'Dim Sum Field Guide',
      description: 'A set of twelve small watercolor and ink illustrations of dim sum dishes, each rendered with botanical illustration precision. Labeled in both English and Chinese. Sold as a complete framed set in a custom grid arrangement.',
      medium: 'watercolor and ink on paper',
      category: 'illustration',
      price: 14000,
      status: 'available',
      isDocumented: false,
      artworkLength: 20, artworkWidth: 24, artworkHeight: 1,
      packedLength: 24, packedWidth: 28, packedHeight: 4,
      packedWeight: 5,
    },
    {
      title: 'Grandmother\'s Apron',
      description: 'Original illustration in ink, watercolor, and collage depicting a well-worn apron filled with objects from the artist\'s grandmother\'s kitchen — a cleaver, bok choy, sesame seeds, and a jade bangle. A meditation on material inheritance.',
      medium: 'ink, watercolor, and collage on paper',
      category: 'illustration',
      price: 20000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 16, artworkWidth: 20, artworkHeight: 0,
      packedLength: 20, packedWidth: 24, packedHeight: 3,
      packedWeight: 1.5,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('maya-chen', 'process/studio')), sortOrder: 0 },
  ],
}

// ============================================================================
// Isaiah Reeves — Detroit, MI — illustration, print — Emerging (30s)
// ============================================================================

const isaiahConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-isaiah-reeves-cognito',
    email: 'isaiah@isaiahreevesart.com',
    fullName: 'Isaiah Reeves',
    avatarUrl: cdnUrl(seedKey('isaiah-reeves', 'profile')),
  },
  profile: {
    displayName: 'Isaiah Reeves',
    slug: 'isaiah-reeves',
    bio: 'Isaiah Reeves is an African-American illustrator and printmaker based in Detroit, Michigan. His large-scale ink drawings and screenprints document the architecture, music, and daily life of Detroit\'s neighborhoods, creating a visual archive of the city\'s ongoing transformation. Reeves draws with brush and India ink on large sheets of paper, creating bold, graphic compositions influenced by the line work of Charles White and Emory Douglas. He holds an MFA from Cranbrook Academy of Art and a BFA from the College for Creative Studies. His work has been exhibited at the Detroit Institute of Arts, the Museum of Contemporary Art Detroit, and the Wright Museum of African American History.',
    location: 'Detroit, MI',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '48201',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('isaiah-reeves', 'cover')),
    profileImageUrl: cdnUrl(seedKey('isaiah-reeves', 'profile')),
    applicationSource: 'direct_application',
    isDemo: true,
  },
  categories: ['illustration', 'print'],
  cvEntries: [
    { type: 'education', title: 'MFA, Print Media', institution: 'Cranbrook Academy of Art, Bloomfield Hills, MI', year: 2020, sortOrder: 1 },
    { type: 'education', title: 'BFA, Illustration', institution: 'College for Creative Studies, Detroit, MI', year: 2016, sortOrder: 2 },
    { type: 'exhibition', title: 'Detroit Unseen', institution: 'Detroit Institute of Arts, Detroit, MI', year: 2025, sortOrder: 3 },
    { type: 'exhibition', title: 'New Work', institution: 'Museum of Contemporary Art Detroit, MI', year: 2023, sortOrder: 4 },
    { type: 'residency', title: 'Artist in Residence', institution: 'Signal Return Letterpress, Detroit, MI', year: 2021, sortOrder: 5 },
    { type: 'award', title: 'Kresge Artist Fellowship', institution: 'Kresge Foundation, Troy, MI', year: 2024, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Cass Corridor, Looking North',
      description: 'Large-scale brush and ink drawing depicting the view north up Cass Avenue, capturing the mix of Victorian houses, industrial buildings, and vacant lots that define the corridor. Bold, confident linework creates a dynamic sense of depth and urban energy.',
      medium: 'India ink on paper',
      category: 'illustration',
      price: 28000,
      status: 'available',
      isDocumented: true,
      artworkLength: 24, artworkWidth: 36, artworkHeight: 0,
      packedLength: 28, packedWidth: 40, packedHeight: 4,
      packedWeight: 3,
    },
    {
      title: 'Motown Session',
      description: 'Three-color screenprint of musicians in a recording studio, inspired by the artist\'s visits to the Motown Museum. Printed in black, gold, and deep blue on heavyweight cream paper. Edition of twenty-five.',
      medium: 'screenprint on cotton rag, edition of 25',
      category: 'print',
      price: 8500,
      status: 'available',
      isDocumented: false,
      artworkLength: 18, artworkWidth: 24, artworkHeight: 0,
      packedLength: 22, packedWidth: 28, packedHeight: 2,
      packedWeight: 1,
    },
    {
      title: 'Barber Shop, Livernois',
      description: 'Brush and ink illustration of the interior of a neighborhood barbershop on Livernois Avenue. Three barbers and their clients are rendered with expressive linework that captures gesture and conversation. The composition places the viewer in the waiting chair.',
      medium: 'India ink on paper',
      category: 'illustration',
      price: 22000,
      status: 'available',
      isDocumented: true,
      artworkLength: 18, artworkWidth: 24, artworkHeight: 0,
      packedLength: 22, packedWidth: 28, packedHeight: 3,
      packedWeight: 2,
    },
    {
      title: 'Michigan Central Station',
      description: 'Detailed ink drawing of the Michigan Central Station, Detroit\'s monumental abandoned train station now under renovation. The drawing captures both the grandeur of the Beaux-Arts architecture and the marks of decades of abandonment.',
      medium: 'India ink on paper',
      category: 'illustration',
      price: 32000,
      status: 'available',
      isDocumented: false,
      artworkLength: 24, artworkWidth: 30, artworkHeight: 0,
      packedLength: 28, packedWidth: 34, packedHeight: 4,
      packedWeight: 2.5,
    },
    {
      title: 'Eastern Market, Saturday',
      description: 'Large brush and ink illustration of Detroit\'s Eastern Market on a bustling Saturday morning. Vendors, shoppers, and produce stalls create a dense, energetic composition. The drawing took three weeks of on-site sketching to complete.',
      medium: 'India ink on paper',
      category: 'illustration',
      price: 35000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 30, artworkWidth: 40, artworkHeight: 0,
      packedLength: 34, packedWidth: 44, packedHeight: 4,
      packedWeight: 3,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('isaiah-reeves', 'process/studio')), sortOrder: 0 },
  ],
}

// ============================================================================
// Nadia Petrov — Philadelphia, PA — illustration, painting — Mid-career (40s)
// ============================================================================

const nadiaConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-nadia-petrov-cognito',
    email: 'nadia@nadiapetrov.com',
    fullName: 'Nadia Petrov',
    avatarUrl: cdnUrl(seedKey('nadia-petrov', 'profile')),
  },
  profile: {
    displayName: 'Nadia Petrov',
    slug: 'nadia-petrov',
    bio: 'Nadia Petrov is a Ukrainian-American illustrator and painter based in Philadelphia. Her gouache paintings and ink illustrations weave together elements of Eastern European folk art, botanical illustration, and contemporary narrative art. Growing up between Kyiv and Philadelphia, Petrov developed a visual language that bridges Slavic decorative traditions with the realism of the Philadelphia school of illustration. She holds an MFA from the Pennsylvania Academy of the Fine Arts and a BFA from the University of the Arts. Her illustrations have appeared in the New Yorker, the Washington Post, and Granta. She has exhibited at the Woodmere Art Museum and the Ukrainian Institute of Modern Art in Chicago.',
    location: 'Philadelphia, PA',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '19106',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('nadia-petrov', 'cover')),
    profileImageUrl: cdnUrl(seedKey('nadia-petrov', 'profile')),
    applicationSource: 'advisor_network',
    isDemo: true,
  },
  categories: ['illustration', 'painting'],
  cvEntries: [
    { type: 'education', title: 'MFA, Painting', institution: 'Pennsylvania Academy of the Fine Arts, Philadelphia, PA', year: 2010, sortOrder: 1 },
    { type: 'education', title: 'BFA, Illustration', institution: 'University of the Arts, Philadelphia, PA', year: 2006, sortOrder: 2 },
    { type: 'exhibition', title: 'Flora and Fable', institution: 'Woodmere Art Museum, Philadelphia, PA', year: 2025, sortOrder: 3 },
    { type: 'exhibition', title: 'Between Worlds', institution: 'Ukrainian Institute of Modern Art, Chicago, IL', year: 2022, sortOrder: 4 },
    { type: 'residency', title: 'Artist in Residence', institution: 'MacDowell, Peterborough, NH', year: 2018, sortOrder: 5 },
    { type: 'press', title: 'Illustrator Spotlight', institution: 'Communication Arts Illustration Annual', year: 2023, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'The Herb Garden',
      description: 'Gouache painting on paper depicting an overflowing herb garden rendered in the style of a botanical field guide. Each plant is labeled in both English and Ukrainian. The painting borders are decorated with traditional vyshyvanka embroidery patterns.',
      medium: 'gouache on paper',
      category: 'illustration',
      price: 16000,
      status: 'available',
      isDocumented: true,
      artworkLength: 14, artworkWidth: 18, artworkHeight: 0,
      packedLength: 18, packedWidth: 22, packedHeight: 3,
      packedWeight: 1,
    },
    {
      title: 'Firebird',
      description: 'Large gouache painting reimagining the Slavic firebird legend in a contemporary Philadelphia rowhouse setting. Rich jewel tones of crimson, gold, and sapphire. The bird perches on a fire escape, its tail feathers trailing down the brick facade.',
      medium: 'gouache on paper',
      category: 'painting',
      price: 35000,
      status: 'available',
      isDocumented: true,
      artworkLength: 22, artworkWidth: 30, artworkHeight: 0,
      packedLength: 26, packedWidth: 34, packedHeight: 4,
      packedWeight: 2,
    },
    {
      title: 'Mushroom Field Guide, Eastern PA',
      description: 'A set of eight gouache illustrations of edible mushrooms found in eastern Pennsylvania forests. Each mushroom is rendered with scientific accuracy and labeled with common and Latin names. Sold as a complete set, matted but unframed.',
      medium: 'gouache on paper',
      category: 'illustration',
      price: 12000,
      status: 'available',
      isDocumented: false,
      artworkLength: 16, artworkWidth: 20, artworkHeight: 0,
      packedLength: 20, packedWidth: 24, packedHeight: 3,
      packedWeight: 1.5,
    },
    {
      title: 'Pysanka Studies',
      description: 'Ink and gouache illustration of five pysanky (Ukrainian Easter eggs) from the artist\'s family collection. Each egg is rendered at three times actual size with the geometric patterns faithfully reproduced. Archival pigment print, signed.',
      medium: 'archival pigment print, edition of 30',
      category: 'illustration',
      price: 5500,
      status: 'available',
      isDocumented: false,
      artworkLength: 11, artworkWidth: 14, artworkHeight: 0,
      packedLength: 15, packedWidth: 18, packedHeight: 2,
      packedWeight: 0.5,
    },
    {
      title: 'Baba\'s Kitchen',
      description: 'Narrative gouache painting depicting the artist\'s grandmother\'s kitchen in Kyiv, filled with jars of preserves, drying herbs, and embroidered linens. The warm palette and detailed still life elements create an intimate portrait of domestic life and cultural continuity.',
      medium: 'gouache on paper',
      category: 'painting',
      price: 28000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 18, artworkWidth: 24, artworkHeight: 0,
      packedLength: 22, packedWidth: 28, packedHeight: 3,
      packedWeight: 1.5,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('nadia-petrov', 'process/studio')), sortOrder: 0 },
  ],
}

export const illustrationArtists: ArtistSeedConfig[] = [
  mayaConfig,
  isaiahConfig,
  nadiaConfig,
]
