import type { ArtistSeedConfig } from '../types'
import { cdnUrl, seedKey } from '../cdn'

// ============================================================================
// Amara Osei — Brooklyn, NY — jewelry, mixed_media — Emerging (30s)
// ============================================================================

const amaraConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-amara-osei-cognito',
    email: 'amara@amaraoseijewelry.com',
    fullName: 'Amara Osei',
    avatarUrl: cdnUrl(seedKey('amara-osei', 'profile')),
  },
  profile: {
    displayName: 'Amara Osei',
    slug: 'amara-osei',
    bio: 'Amara Osei is a Ghanaian-American jeweler and mixed media artist based in Brooklyn, New York. Her work reinterprets the lost-wax casting traditions of Akan goldweights through a contemporary lens, creating wearable sculptures in brass, bronze, and recycled gold. Each piece begins as a hand-carved wax original, connecting her studio practice to the centuries-old casting techniques of her Ashanti heritage. Osei holds an MFA from Pratt Institute and a BFA from Howard University. She has exhibited at the Museum of Arts and Design, the Studio Museum in Harlem, and the Society of North American Goldsmiths conference. Her jewelry has been featured in Vogue and Essence magazines.',
    location: 'Brooklyn, NY',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '11216',
    status: 'approved',
    commissionsOpen: true,
    coverImageUrl: cdnUrl(seedKey('amara-osei', 'cover')),
    profileImageUrl: cdnUrl(seedKey('amara-osei', 'profile')),
    applicationSource: 'direct_application',
    isDemo: true,
  },
  categories: ['jewelry', 'mixed_media'],
  cvEntries: [
    { type: 'education', title: 'MFA, Jewelry and Metalsmithing', institution: 'Pratt Institute, Brooklyn, NY', year: 2019, sortOrder: 1 },
    { type: 'education', title: 'BFA, Fine Arts', institution: 'Howard University, Washington, DC', year: 2015, sortOrder: 2 },
    { type: 'exhibition', title: 'Adornment as Archive', institution: 'Museum of Arts and Design, New York, NY', year: 2025, sortOrder: 3 },
    { type: 'exhibition', title: 'SNAG Annual Conference Exhibition', institution: 'Society of North American Goldsmiths, Chicago, IL', year: 2023, sortOrder: 4 },
    { type: 'residency', title: 'Artist in Residence', institution: 'Penland School of Craft, Bakersville, NC', year: 2022, sortOrder: 5 },
    { type: 'press', title: 'Feature: New Voices in American Jewelry', institution: 'American Craft Magazine', year: 2024, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Sankofa Cuff',
      description: 'Lost-wax cast brass cuff bracelet inspired by the Sankofa symbol. The cuff features a stylized bird form reaching backward, cast from a hand-carved wax original. Finished with a brushed patina that highlights the texture of the wax carving process.',
      medium: 'lost-wax cast brass',
      category: 'jewelry',
      price: 18000,
      status: 'available',
      isDocumented: true,
      artworkLength: 3, artworkWidth: 2.5, artworkHeight: 2.5,
      packedLength: 7, packedWidth: 6.5, packedHeight: 6.5,
      packedWeight: 1,
    },
    {
      title: 'Goldweight Earrings, Geometric',
      description: 'Pair of drop earrings cast in recycled gold-filled wire, inspired by the geometric patterns of Akan goldweights. Each earring is a unique casting from a hand-carved wax original. French wire ear hooks in 14k gold-filled.',
      medium: 'gold-filled, lost-wax cast',
      category: 'jewelry',
      price: 12000,
      status: 'available',
      isDocumented: false,
      artworkLength: 0.5, artworkWidth: 0.75, artworkHeight: 2,
      packedLength: 4.5, packedWidth: 4.75, packedHeight: 6,
      packedWeight: 0.5,
    },
    {
      title: 'Adinkra Ring, Gye Nyame',
      description: 'Signet-style ring cast in bronze featuring the Gye Nyame symbol, meaning "except God" in Akan philosophy. The ring face is carved with fine detail from a wax original, with a comfortable band width for everyday wear.',
      medium: 'lost-wax cast bronze',
      category: 'jewelry',
      price: 8500,
      status: 'available',
      isDocumented: false,
      artworkLength: 1, artworkWidth: 1, artworkHeight: 0.75,
      packedLength: 5, packedWidth: 5, packedHeight: 4.75,
      packedWeight: 0.5,
    },
    {
      title: 'Kente Pendant, Large',
      description: 'Statement necklace featuring a large pendant inspired by kente cloth weaving patterns. Cast in brass from a hand-carved wax original and suspended from a hand-forged brass chain. The pendant surface captures the crosshatch texture of woven cloth.',
      medium: 'lost-wax cast brass, hand-forged chain',
      category: 'jewelry',
      price: 22000,
      status: 'available',
      isDocumented: true,
      artworkLength: 2, artworkWidth: 2, artworkHeight: 0.25,
      packedLength: 6, packedWidth: 6, packedHeight: 4.25,
      packedWeight: 0.5,
    },
    {
      title: 'Goldweight Brooch, Bird',
      description: 'Figurative brooch cast in recycled gold-filled metal depicting a stylized bird. The form references Akan goldweight birds used historically to weigh gold dust for trade. Pin back closure.',
      medium: 'recycled gold-filled, lost-wax cast',
      category: 'jewelry',
      price: 15000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 1.5, artworkWidth: 2, artworkHeight: 0.5,
      packedLength: 5.5, packedWidth: 6, packedHeight: 4.5,
      packedWeight: 0.5,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('amara-osei', 'process/studio')), sortOrder: 0 },
  ],
}

// ============================================================================
// Rosa Gutierrez — Tucson, AZ — jewelry, ceramics — Mid-career (40s)
// ============================================================================

const rosaConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-rosa-gutierrez-cognito',
    email: 'rosa@rosagutierrezstudio.com',
    fullName: 'Rosa Gutierrez',
    avatarUrl: cdnUrl(seedKey('rosa-gutierrez', 'profile')),
  },
  profile: {
    displayName: 'Rosa Gutierrez',
    slug: 'rosa-gutierrez',
    bio: 'Rosa Gutierrez is a Mexican jeweler and ceramicist based in Tucson, Arizona. Born in Oaxaca and trained in the silversmithing traditions of Taxco, her work bridges traditional Mexican metalwork with Sonoran desert aesthetics. She combines hand-fabricated sterling silver with locally sourced turquoise, copper, and ceramic elements she fires in her backyard kiln. Gutierrez holds an MFA from the University of Arizona and apprenticed with master silversmith Roberto Torres in Taxco, Guerrero. She has exhibited at the Tucson Museum of Art, SOFA Chicago, and the Smithsonian Craft Show. Her work explores the border region as both a geographic and cultural threshold.',
    location: 'Tucson, AZ',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '85701',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('rosa-gutierrez', 'cover')),
    profileImageUrl: cdnUrl(seedKey('rosa-gutierrez', 'profile')),
    applicationSource: 'advisor_network',
    isDemo: true,
  },
  categories: ['jewelry', 'ceramics'],
  cvEntries: [
    { type: 'education', title: 'MFA, Metals', institution: 'University of Arizona, Tucson, AZ', year: 2008, sortOrder: 1 },
    { type: 'education', title: 'Silversmithing Apprenticeship', institution: 'Taller Torres, Taxco, Guerrero, Mexico', year: 2004, sortOrder: 2 },
    { type: 'exhibition', title: 'Borderlands', institution: 'Tucson Museum of Art, Tucson, AZ', year: 2024, sortOrder: 3 },
    { type: 'exhibition', title: 'Smithsonian Craft Show', institution: 'National Building Museum, Washington, DC', year: 2022, sortOrder: 4 },
    { type: 'residency', title: 'Artist in Residence', institution: 'Arrowmont School of Arts and Crafts, Gatlinburg, TN', year: 2016, sortOrder: 5 },
    { type: 'award', title: 'Arizona Commission on the Arts Fellowship', institution: 'Phoenix, AZ', year: 2021, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Sonoran Cuff, turquoise',
      description: 'Hand-fabricated sterling silver cuff bracelet set with a Sleeping Beauty turquoise cabochon from the Globe, Arizona mine. The textured silver surface is created by hammering with a traditional Taxco technique called martillado, giving each cuff a unique pattern.',
      medium: 'sterling silver, turquoise',
      category: 'jewelry',
      price: 22000,
      status: 'available',
      isDocumented: true,
      artworkLength: 2.5, artworkWidth: 2.5, artworkHeight: 1.5,
      packedLength: 6.5, packedWidth: 6.5, packedHeight: 5.5,
      packedWeight: 1,
    },
    {
      title: 'Desert Bloom Earrings',
      description: 'Sterling silver drop earrings featuring hand-formed petal shapes inspired by saguaro cactus flowers. Each earring has a small ceramic bead fired with a turquoise glaze that the artist makes in her own kiln. French hook ear wires.',
      medium: 'sterling silver, ceramic',
      category: 'jewelry',
      price: 9500,
      status: 'available',
      isDocumented: false,
      artworkLength: 0.75, artworkWidth: 0.75, artworkHeight: 2.5,
      packedLength: 4.75, packedWidth: 4.75, packedHeight: 6.5,
      packedWeight: 0.5,
    },
    {
      title: 'Milagro Bowl',
      description: 'Hand-thrown earthenware bowl with copper glaze and small sterling silver milagro charms pressed into the rim before firing. The bowl form references Oaxacan chocolate vessels while the milagros connect to the folk art tradition of devotional offerings.',
      medium: 'earthenware, copper glaze, sterling silver',
      category: 'ceramics',
      price: 14000,
      status: 'available',
      isDocumented: true,
      artworkLength: 7, artworkWidth: 7, artworkHeight: 4,
      packedLength: 11, packedWidth: 11, packedHeight: 8,
      packedWeight: 3,
    },
    {
      title: 'Copper and Silver Ring',
      description: 'Bi-metal ring combining sterling silver and hand-patinated copper in a traditional married metals technique. The two metals are fused and then shaped into a comfortable wide band. Each ring develops a unique patina over time.',
      medium: 'sterling silver, copper',
      category: 'jewelry',
      price: 6500,
      status: 'available',
      isDocumented: false,
      artworkLength: 1, artworkWidth: 1, artworkHeight: 0.5,
      packedLength: 5, packedWidth: 5, packedHeight: 4.5,
      packedWeight: 0.5,
    },
    {
      title: 'Nopal Brooch',
      description: 'Hand-fabricated sterling silver brooch in the form of a prickly pear cactus pad. The surface is chased and repoussé to create dimensional thorns and texture. Set with a small oval of chrysoprase suggesting the green flesh of the fruit.',
      medium: 'sterling silver, chrysoprase',
      category: 'jewelry',
      price: 16000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 2, artworkWidth: 2.5, artworkHeight: 0.5,
      packedLength: 6, packedWidth: 6.5, packedHeight: 4.5,
      packedWeight: 0.5,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('rosa-gutierrez', 'process/studio')), sortOrder: 0 },
  ],
}

// ============================================================================
// Lena Volkov — Pittsburgh, PA — jewelry, fibers — Emerging (20s)
// ============================================================================

const lenaConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-lena-volkov-cognito',
    email: 'lena@lenavolkovstudio.com',
    fullName: 'Lena Volkov',
    avatarUrl: cdnUrl(seedKey('lena-volkov', 'profile')),
  },
  profile: {
    displayName: 'Lena Volkov',
    slug: 'lena-volkov',
    bio: 'Lena Volkov is a Russian-American jeweler and fiber artist based in Pittsburgh, Pennsylvania. Her work combines delicate metalsmithing with textile techniques — wrapping, knotting, and weaving fine silver and gold wire into structures that echo the lacework of her grandmother\'s needlework from Saint Petersburg. Volkov holds an MFA from Carnegie Mellon University and a BFA from Tyler School of Art. She has exhibited at the Pittsburgh Glass Center, the Metal Museum in Memphis, and the Philadelphia Museum of Art Craft Show. Her practice explores the tension between the precious and the fragile, the industrial and the handmade.',
    location: 'Pittsburgh, PA',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '15222',
    status: 'approved',
    commissionsOpen: true,
    coverImageUrl: cdnUrl(seedKey('lena-volkov', 'cover')),
    profileImageUrl: cdnUrl(seedKey('lena-volkov', 'profile')),
    applicationSource: 'direct_application',
    isDemo: true,
  },
  categories: ['jewelry', 'fibers'],
  cvEntries: [
    { type: 'education', title: 'MFA, Metals and Jewelry', institution: 'Carnegie Mellon University, Pittsburgh, PA', year: 2024, sortOrder: 1 },
    { type: 'education', title: 'BFA, Metals/Jewelry/CAD-CAM', institution: 'Tyler School of Art, Philadelphia, PA', year: 2021, sortOrder: 2 },
    { type: 'exhibition', title: 'Woven Metal', institution: 'Metal Museum, Memphis, TN', year: 2025, sortOrder: 3 },
    { type: 'exhibition', title: 'Emerging Makers', institution: 'Pittsburgh Glass Center, Pittsburgh, PA', year: 2024, sortOrder: 4 },
    { type: 'award', title: 'Windgate-Lamar Fellowship', institution: 'Center for Craft, Asheville, NC', year: 2023, sortOrder: 5 },
  ],
  listings: [
    {
      title: 'Lace Collar Necklace',
      description: 'A collar-style necklace of intricately woven fine silver wire, creating an openwork pattern that mimics needle lace. The piece drapes like textile but has the cool weight of metal. Clasp hidden within the woven structure.',
      medium: 'fine silver wire, hand-woven',
      category: 'jewelry',
      price: 22000,
      status: 'available',
      isDocumented: true,
      artworkLength: 6, artworkWidth: 6, artworkHeight: 0.25,
      packedLength: 10, packedWidth: 10, packedHeight: 4.25,
      packedWeight: 0.5,
    },
    {
      title: 'Knot Earrings, Gold',
      description: 'Drop earrings featuring sailor\'s knots tied in 14k gold-filled wire. Each knot is tied by hand, making every pair slightly unique. Lightweight despite their visual complexity. French wire ear hooks.',
      medium: '14k gold-filled wire',
      category: 'jewelry',
      price: 8500,
      status: 'available',
      isDocumented: false,
      artworkLength: 0.5, artworkWidth: 0.5, artworkHeight: 1.5,
      packedLength: 4.5, packedWidth: 4.5, packedHeight: 5.5,
      packedWeight: 0.5,
    },
    {
      title: 'Steel Lace Cuff',
      description: 'Cuff bracelet woven from oxidized steel wire and fine silver, creating a two-tone lace pattern. The contrast between the dark steel and bright silver echoes Pittsburgh\'s industrial heritage. Hinged for easy wearing.',
      medium: 'steel wire, fine silver, hand-woven',
      category: 'jewelry',
      price: 16000,
      status: 'available',
      isDocumented: true,
      artworkLength: 3, artworkWidth: 2.5, artworkHeight: 2,
      packedLength: 7, packedWidth: 6.5, packedHeight: 6,
      packedWeight: 1,
    },
    {
      title: 'Woven Ring, Silver',
      description: 'A wide band ring woven from fine silver wire in a basket weave pattern. The surface has an organic, textile-like texture that catches light from multiple angles. Surprisingly comfortable for daily wear.',
      medium: 'fine silver wire, hand-woven',
      category: 'jewelry',
      price: 6500,
      status: 'available',
      isDocumented: false,
      artworkLength: 1, artworkWidth: 1, artworkHeight: 0.5,
      packedLength: 5, packedWidth: 5, packedHeight: 4.5,
      packedWeight: 0.5,
    },
    {
      title: 'Grandmother\'s Thread Brooch',
      description: 'Brooch combining woven fine silver wire with a fragment of vintage linen thread from the artist\'s family collection. The metal wire and textile thread are woven together, blurring the line between jewelry and textile. Sterling pin mechanism.',
      medium: 'fine silver wire, vintage linen, sterling silver',
      category: 'jewelry',
      price: 12000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 2, artworkWidth: 2.5, artworkHeight: 0.5,
      packedLength: 6, packedWidth: 6.5, packedHeight: 4.5,
      packedWeight: 0.5,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('lena-volkov', 'process/studio')), sortOrder: 0 },
  ],
}

// ============================================================================
// Sophie Tremblay — Burlington, VT — jewelry, fibers — Emerging (30s)
// ============================================================================

const sophieConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-sophie-tremblay-cognito',
    email: 'sophie@sophietremblayjewelry.com',
    fullName: 'Sophie Tremblay',
    avatarUrl: cdnUrl(seedKey('sophie-tremblay', 'profile')),
  },
  profile: {
    displayName: 'Sophie Tremblay',
    slug: 'sophie-tremblay',
    bio: 'Sophie Tremblay is a French-Canadian-American jeweler and fiber artist based in Burlington, Vermont. Her work combines traditional enamelwork on copper and silver with hand-dyed silk and linen elements, creating pieces that sit between jewelry and wearable textile art. Inspired by the landscapes of the Lake Champlain region and the folk traditions of Québec, her color palette draws from seasonal changes in the northern Vermont landscape. Tremblay holds an MFA from the University of Wisconsin-Madison and a BFA from the Maine College of Art. She has exhibited at the Vermont Studio Center, the Burlington City Arts gallery, and the Philadelphia Museum of Art Craft Show.',
    location: 'Burlington, VT',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '05401',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('sophie-tremblay', 'cover')),
    profileImageUrl: cdnUrl(seedKey('sophie-tremblay', 'profile')),
    applicationSource: 'direct_application',
    isDemo: true,
  },
  categories: ['jewelry', 'fibers'],
  cvEntries: [
    { type: 'education', title: 'MFA, Art (Metals)', institution: 'University of Wisconsin-Madison, WI', year: 2019, sortOrder: 1 },
    { type: 'education', title: 'BFA, Metalsmithing and Jewelry', institution: 'Maine College of Art, Portland, ME', year: 2015, sortOrder: 2 },
    { type: 'exhibition', title: 'Northern Color', institution: 'Burlington City Arts, Burlington, VT', year: 2025, sortOrder: 3 },
    { type: 'exhibition', title: 'Philadelphia Museum of Art Craft Show', institution: 'Philadelphia, PA', year: 2023, sortOrder: 4 },
    { type: 'residency', title: 'Artist in Residence', institution: 'Vermont Studio Center, Johnson, VT', year: 2021, sortOrder: 5 },
    { type: 'award', title: 'Vermont Arts Council Creation Grant', institution: 'Montpelier, VT', year: 2024, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Enamel Pendant, Autumn',
      description: 'Copper pendant with vitreous enamel in warm autumn colors — deep red, amber, and golden yellow. The enamel is applied in multiple firings to build depth and translucency. Suspended from a hand-dyed silk cord in a complementary burnt orange.',
      medium: 'copper, vitreous enamel, hand-dyed silk',
      category: 'jewelry',
      price: 9500,
      status: 'available',
      isDocumented: true,
      artworkLength: 1.5, artworkWidth: 1.5, artworkHeight: 0.25,
      packedLength: 5.5, packedWidth: 5.5, packedHeight: 4.25,
      packedWeight: 0.5,
    },
    {
      title: 'Lake Champlain Brooch',
      description: 'Sterling silver brooch with cloisonné enamel depicting an abstract interpretation of Lake Champlain seen from above. Blues and greens are separated by fine silver wire partitions in the traditional cloisonné technique.',
      medium: 'sterling silver, cloisonné enamel',
      category: 'jewelry',
      price: 14000,
      status: 'available',
      isDocumented: true,
      artworkLength: 2, artworkWidth: 1.5, artworkHeight: 0.5,
      packedLength: 6, packedWidth: 5.5, packedHeight: 4.5,
      packedWeight: 0.5,
    },
    {
      title: 'Woven Linen Bracelet, Indigo',
      description: 'Hand-woven linen bracelet dyed with natural indigo. The weave structure creates a subtle pattern of darker and lighter blues. Sterling silver toggle clasp handmade in the studio. Comfortable and lightweight for everyday wear.',
      medium: 'hand-woven linen, natural indigo dye, sterling silver',
      category: 'fibers',
      price: 6500,
      status: 'available',
      isDocumented: false,
      artworkLength: 7, artworkWidth: 1, artworkHeight: 0.25,
      packedLength: 5, packedWidth: 5, packedHeight: 4.25,
      packedWeight: 0.5,
    },
    {
      title: 'Enamel Stud Earrings, Winter',
      description: 'Small round stud earrings with vitreous enamel in cool winter tones — ice blue, lavender, and white. Each pair is fired individually, resulting in subtle color variations. Sterling silver post and butterfly back.',
      medium: 'copper, vitreous enamel, sterling silver',
      category: 'jewelry',
      price: 4800,
      status: 'available',
      isDocumented: false,
      artworkLength: 0.5, artworkWidth: 0.5, artworkHeight: 0.25,
      packedLength: 4.5, packedWidth: 4.5, packedHeight: 4.25,
      packedWeight: 0.5,
    },
    {
      title: 'Enamel Pendant, Spring Melt',
      description: 'Pendant featuring layered enamel in blues and greens evoking the spring melt on the Winooski River. Three firings build depth and luminosity. Hung on a hand-braided silk cord in moss green.',
      medium: 'copper, vitreous enamel, hand-dyed silk',
      category: 'jewelry',
      price: 11000,
      status: 'sold',
      isDocumented: false,
      artworkLength: 1.5, artworkWidth: 1, artworkHeight: 0.25,
      packedLength: 5.5, packedWidth: 5, packedHeight: 4.25,
      packedWeight: 0.5,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('sophie-tremblay', 'process/studio')), sortOrder: 0 },
  ],
}

export const jewelryArtists: ArtistSeedConfig[] = [
  amaraConfig,
  rosaConfig,
  lenaConfig,
  sophieConfig,
]
