import type { ArtistSeedConfig } from '../types'
import { cdnUrl, seedKey } from '../cdn'

// ============================================================================
// Elena Cordova — Santa Fe, NM — painting, mixed_media — Mid-career (40s)
// ============================================================================

const elenaConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-elena-cordova-cognito',
    email: 'elena@elenacordova-art.com',
    fullName: 'Elena Cordova',
    avatarUrl: cdnUrl(seedKey('elena-cordova', 'profile')),
  },
  profile: {
    displayName: 'Elena Cordova',
    slug: 'elena-cordova',
    bio: 'Elena Cordova is a Mexican-American painter working at the intersection of landscape, memory, and cultural identity. Based in Santa Fe, New Mexico, her paintings layer translucent washes of oil and natural pigments sourced from the high desert to evoke the terrain of the American Southwest and her family\'s roots in Chihuahua. Cordova holds an MFA from Yale School of Art and a BFA from the University of New Mexico. Her work has been exhibited at the Harwood Museum in Taos, the National Hispanic Cultural Center, and Headlands Center for the Arts. She is a recipient of a Joan Mitchell Foundation grant and a MacDowell fellowship.',
    location: 'Santa Fe, NM',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '87501',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('elena-cordova', 'cover')),
    profileImageUrl: cdnUrl(seedKey('elena-cordova', 'profile')),
    applicationSource: 'advisor_network',
    isDemo: true,
  },
  categories: ['painting', 'mixed_media'],
  cvEntries: [
    { type: 'education', title: 'MFA, Painting and Printmaking', institution: 'Yale School of Art, New Haven, CT', year: 2012, sortOrder: 1 },
    { type: 'education', title: 'BFA, Studio Art', institution: 'University of New Mexico, Albuquerque, NM', year: 2008, sortOrder: 2 },
    { type: 'exhibition', title: 'Tierra y Tiempo', institution: 'Harwood Museum of Art, Taos, NM', year: 2025, sortOrder: 3 },
    { type: 'exhibition', title: 'Desert Frequencies', institution: 'National Hispanic Cultural Center, Albuquerque, NM', year: 2023, sortOrder: 4 },
    { type: 'residency', title: 'Artist in Residence', institution: 'MacDowell, Peterborough, NH', year: 2021, sortOrder: 5 },
    { type: 'award', title: 'Painters & Sculptors Grant', institution: 'Joan Mitchell Foundation', year: 2020, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Arroyos at Dusk',
      description: 'Oil on canvas painting depicting the dry washes near Abiquiu at twilight. Built up in thin glazes of earth-toned pigment over a warm ground, the surface captures the fleeting violet light of a high-desert evening. Unframed on stretched canvas with painted edges.',
      medium: 'oil on canvas',
      category: 'painting',
      price: 42000,
      status: 'available',
      isDocumented: true,
      artworkLength: 36, artworkWidth: 48, artworkHeight: 1.5,
      packedLength: 40, packedWidth: 52, packedHeight: 5,
      packedWeight: 12,
    },
    {
      title: 'Acequia Study No. 3',
      description: 'Small-scale oil study of an irrigation ditch winding through cottonwood trees. Painted en plein air near the Santa Cruz River. Loose brushwork captures dappled sunlight on moving water. Unframed on cradled panel.',
      medium: 'oil on cradled panel',
      category: 'painting',
      price: 18000,
      status: 'available',
      isDocumented: false,
      artworkLength: 12, artworkWidth: 16, artworkHeight: 1.5,
      packedLength: 16, packedWidth: 20, packedHeight: 5,
      packedWeight: 4,
    },
    {
      title: 'Red Earth, Blue Shadow',
      description: 'Landscape painting exploring the complementary color dynamics of iron-rich soil against cool mountain shadows. Oil and natural pigment on linen. The ochre pigment was hand-ground from stone collected near Ghost Ranch.',
      medium: 'oil and natural pigment on linen',
      category: 'painting',
      price: 35000,
      status: 'available',
      isDocumented: true,
      artworkLength: 30, artworkWidth: 40, artworkHeight: 1.5,
      packedLength: 34, packedWidth: 44, packedHeight: 5,
      packedWeight: 10,
    },
    {
      title: 'Chamisa in October',
      description: 'A study of the bright yellow chamisa bushes that bloom along the Rio Grande corridor in autumn. Painted with a limited palette of cadmium yellow, raw umber, and ultramarine. Oil on panel.',
      medium: 'oil on panel',
      category: 'painting',
      price: 14000,
      status: 'available',
      isDocumented: false,
      artworkLength: 10, artworkWidth: 14, artworkHeight: 1,
      packedLength: 14, packedWidth: 18, packedHeight: 4,
      packedWeight: 3,
    },
    {
      title: 'Madre Tierra (sold)',
      description: 'Large-format painting combining oil paint with hand-ground desert pigments on raw linen. An exploration of maternal land and inherited geography.',
      medium: 'oil and natural pigment on linen',
      category: 'painting',
      price: 55000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 48, artworkWidth: 60, artworkHeight: 2,
      packedLength: 52, packedWidth: 64, packedHeight: 6,
      packedWeight: 18,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('elena-cordova', 'process/studio')), sortOrder: 0 },
  ],
}

// ============================================================================
// James Okafor — Atlanta, GA — painting, illustration — Emerging (30s)
// ============================================================================

const jamesConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-james-okafor-cognito',
    email: 'james@jamesokaforart.com',
    fullName: 'James Okafor',
    avatarUrl: cdnUrl(seedKey('james-okafor', 'profile')),
  },
  profile: {
    displayName: 'James Okafor',
    slug: 'james-okafor',
    bio: 'James Okafor is a Nigerian-American painter and illustrator based in Atlanta, Georgia. His acrylic and gouache paintings draw from Igbo visual traditions, contemporary street culture, and the everyday rituals of the African diaspora in the American South. Okafor received his MFA from the Lamar Dodd School of Art at the University of Georgia and a BA in Visual Arts from Morehouse College. He has exhibited at the High Museum of Art, Hammonds House Museum, and Kavi Gupta Gallery. His work explores portraiture as a form of cultural documentation, centering Black joy, community, and intergenerational storytelling.',
    location: 'Atlanta, GA',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '30312',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('james-okafor', 'cover')),
    profileImageUrl: cdnUrl(seedKey('james-okafor', 'profile')),
    applicationSource: 'direct_application',
    isDemo: true,
  },
  categories: ['painting', 'illustration'],
  cvEntries: [
    { type: 'education', title: 'MFA, Painting and Drawing', institution: 'University of Georgia, Athens, GA', year: 2021, sortOrder: 1 },
    { type: 'education', title: 'BA, Visual Arts', institution: 'Morehouse College, Atlanta, GA', year: 2017, sortOrder: 2 },
    { type: 'exhibition', title: 'New Voices in Southern Art', institution: 'High Museum of Art, Atlanta, GA', year: 2024, sortOrder: 3 },
    { type: 'exhibition', title: 'Homegoing', institution: 'Hammonds House Museum, Atlanta, GA', year: 2023, sortOrder: 4 },
    { type: 'residency', title: 'Artist in Residence', institution: 'Skowhegan School of Painting and Sculpture, ME', year: 2022, sortOrder: 5 },
    { type: 'award', title: 'Emerging Artist Grant', institution: 'Atlanta Contemporary, Atlanta, GA', year: 2023, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Sunday Table',
      description: 'Acrylic portrait of a multigenerational family gathered around a Sunday dinner table. Rich, saturated colors and patterned textiles frame the figures. The composition draws from the artist\'s memories of family gatherings in Lagos and Atlanta.',
      medium: 'acrylic on canvas',
      category: 'painting',
      price: 32000,
      status: 'available',
      isDocumented: true,
      artworkLength: 30, artworkWidth: 40, artworkHeight: 1.5,
      packedLength: 34, packedWidth: 44, packedHeight: 5,
      packedWeight: 10,
    },
    {
      title: 'Corner Store',
      description: 'Gouache painting depicting the interior of a neighborhood corner store. Shelves lined with bright packaging create a mosaic of color and pattern. A quiet meditation on the small businesses that anchor immigrant communities.',
      medium: 'gouache on paper',
      category: 'painting',
      price: 15000,
      status: 'available',
      isDocumented: false,
      artworkLength: 18, artworkWidth: 24, artworkHeight: 0,
      packedLength: 22, packedWidth: 28, packedHeight: 3,
      packedWeight: 2,
    },
    {
      title: 'Wash Day',
      description: 'Acrylic and collage portrait of a young woman braiding hair on a front porch. The painting combines bold figure work with cut-paper elements from West African textiles sourced from the artist\'s family collection.',
      medium: 'acrylic and collage on canvas',
      category: 'painting',
      price: 28000,
      status: 'available',
      isDocumented: true,
      artworkLength: 24, artworkWidth: 30, artworkHeight: 1.5,
      packedLength: 28, packedWidth: 34, packedHeight: 5,
      packedWeight: 8,
    },
    {
      title: 'Lunchtime, Decatur',
      description: 'Small-format gouache study of workers eating lunch outside a construction site. Warm afternoon light and casual postures create an intimate snapshot of everyday life in metro Atlanta.',
      medium: 'gouache on paper',
      category: 'illustration',
      price: 8500,
      status: 'available',
      isDocumented: false,
      artworkLength: 9, artworkWidth: 12, artworkHeight: 0,
      packedLength: 13, packedWidth: 16, packedHeight: 3,
      packedWeight: 1,
    },
    {
      title: 'Elders',
      description: 'Double portrait in acrylic depicting two seated elders in conversation. The composition references both classical Nigerian portraiture and the American tradition of porch sitting. Warm earth tones and gold leaf accents.',
      medium: 'acrylic and gold leaf on canvas',
      category: 'painting',
      price: 38000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 36, artworkWidth: 48, artworkHeight: 1.5,
      packedLength: 40, packedWidth: 52, packedHeight: 5,
      packedWeight: 14,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('james-okafor', 'process/studio')), sortOrder: 0 },
  ],
}

// ============================================================================
// Priya Mehta — Portland, OR — painting, print — Established (50s)
// ============================================================================

const priyaConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-priya-mehta-cognito',
    email: 'priya@priyamehtaart.com',
    fullName: 'Priya Mehta',
    avatarUrl: cdnUrl(seedKey('priya-mehta', 'profile')),
  },
  profile: {
    displayName: 'Priya Mehta',
    slug: 'priya-mehta',
    bio: 'Priya Mehta is an Indian-American painter and printmaker whose work bridges the miniature painting traditions of Rajasthan with contemporary abstraction. Based in Portland, Oregon, Mehta builds densely layered compositions using watercolor, gouache, and hand-carved woodblock prints on handmade paper. Her paintings explore themes of migration, botanical memory, and the patterns that connect South Asian textile design to the natural world. She holds an MFA from the Rhode Island School of Design and a BFA from the School of the Art Institute of Chicago. Mehta has exhibited internationally, including at the Portland Art Museum, Asia Society, and the Kochi-Muziris Biennale.',
    location: 'Portland, OR',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '97201',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('priya-mehta', 'cover')),
    profileImageUrl: cdnUrl(seedKey('priya-mehta', 'profile')),
    applicationSource: 'advisor_network',
    isDemo: true,
  },
  categories: ['painting', 'print'],
  cvEntries: [
    { type: 'education', title: 'MFA, Painting', institution: 'Rhode Island School of Design, Providence, RI', year: 2001, sortOrder: 1 },
    { type: 'education', title: 'BFA, Painting and Drawing', institution: 'School of the Art Institute of Chicago, IL', year: 1997, sortOrder: 2 },
    { type: 'exhibition', title: 'Inherited Gardens', institution: 'Portland Art Museum, Portland, OR', year: 2024, sortOrder: 3 },
    { type: 'exhibition', title: 'Roots and Routes', institution: 'Asia Society, New York, NY', year: 2022, sortOrder: 4 },
    { type: 'residency', title: 'Artist in Residence', institution: 'Yaddo, Saratoga Springs, NY', year: 2019, sortOrder: 5 },
    { type: 'award', title: 'Oregon Arts Commission Individual Artist Fellowship', institution: 'Salem, OR', year: 2023, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Garden of Borrowed Light',
      description: 'Watercolor and gouache painting on handmade Khadi paper. Intricate botanical forms inspired by Mughal garden miniatures dissolve into abstract washes of indigo and saffron. The composition unfolds like a map of inherited memory.',
      medium: 'watercolor and gouache on handmade paper',
      category: 'painting',
      price: 45000,
      status: 'available',
      isDocumented: true,
      artworkLength: 22, artworkWidth: 30, artworkHeight: 0,
      packedLength: 26, packedWidth: 34, packedHeight: 4,
      packedWeight: 3,
    },
    {
      title: 'Migration Pattern No. 7',
      description: 'Hand-carved woodblock print on Japanese washi paper, edition of fifteen. Overlapping bird forms create a dense lattice pattern inspired by Rajasthani jali screens. Printed in two colors using water-based inks.',
      medium: 'woodblock print on washi, edition of 15',
      category: 'print',
      price: 12000,
      status: 'available',
      isDocumented: false,
      artworkLength: 18, artworkWidth: 24, artworkHeight: 0,
      packedLength: 22, packedWidth: 28, packedHeight: 3,
      packedWeight: 1.5,
    },
    {
      title: 'Spice Route',
      description: 'Mixed media painting combining watercolor washes with hand-printed woodblock elements. Botanical illustrations of turmeric, cardamom, and saffron float across a field of warm ochre, mapping the historic spice trade routes.',
      medium: 'watercolor and woodblock print on paper',
      category: 'painting',
      price: 28000,
      status: 'available',
      isDocumented: true,
      artworkLength: 20, artworkWidth: 26, artworkHeight: 0,
      packedLength: 24, packedWidth: 30, packedHeight: 4,
      packedWeight: 2,
    },
    {
      title: 'Lattice Study, Amber',
      description: 'Small woodblock print exploring the geometric patterns found in the latticed windows of Amber Fort. Printed in a single color of burnt sienna ink on cream washi. Edition of twenty-five.',
      medium: 'woodblock print on washi, edition of 25',
      category: 'print',
      price: 6500,
      status: 'available',
      isDocumented: false,
      artworkLength: 10, artworkWidth: 10, artworkHeight: 0,
      packedLength: 14, packedWidth: 14, packedHeight: 3,
      packedWeight: 1,
    },
    {
      title: 'Monsoon',
      description: 'Large-format watercolor and gouache painting depicting rain falling on a garden of marigolds. Layers of transparent color build a shimmering, atmospheric depth. Painted on stretched Khadi paper.',
      medium: 'watercolor and gouache on handmade paper',
      category: 'painting',
      price: 52000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 30, artworkWidth: 40, artworkHeight: 0,
      packedLength: 34, packedWidth: 44, packedHeight: 5,
      packedWeight: 4,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('priya-mehta', 'process/studio')), sortOrder: 0 },
  ],
}

// ============================================================================
// Sunhi Park — Chicago, IL — painting, ceramics — Emerging (20s)
// ============================================================================

const sunhiConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-sunhi-park-cognito',
    email: 'sunhi@sunhipark.com',
    fullName: 'Sunhi Park',
    avatarUrl: cdnUrl(seedKey('sunhi-park', 'profile')),
  },
  profile: {
    displayName: 'Sunhi Park',
    slug: 'sunhi-park',
    bio: 'Sunhi Park is a Korean-American artist working across painting and ceramics. Born in Seoul and raised in Chicago, her practice examines the quiet tension between the two cultures she inhabits. Her paintings use translucent layers of acrylic and hanji paper on panel, while her ceramic work takes the form of small functional vessels glazed in celadon and white. Park holds an MFA from the School of the Art Institute of Chicago and a BA from Northwestern University. She has exhibited at the Chicago Cultural Center, the Museum of Contemporary Art Chicago, and Roots and Culture gallery. She was a 2024 BOLT resident at the Chicago Artists Coalition.',
    location: 'Chicago, IL',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '60622',
    status: 'approved',
    commissionsOpen: true,
    coverImageUrl: cdnUrl(seedKey('sunhi-park', 'cover')),
    profileImageUrl: cdnUrl(seedKey('sunhi-park', 'profile')),
    applicationSource: 'direct_application',
    isDemo: true,
  },
  categories: ['painting', 'ceramics'],
  cvEntries: [
    { type: 'education', title: 'MFA, Painting and Drawing', institution: 'School of the Art Institute of Chicago, IL', year: 2024, sortOrder: 1 },
    { type: 'education', title: 'BA, Art Theory and Practice', institution: 'Northwestern University, Evanston, IL', year: 2021, sortOrder: 2 },
    { type: 'exhibition', title: 'Between Languages', institution: 'Chicago Cultural Center, Chicago, IL', year: 2025, sortOrder: 3 },
    { type: 'exhibition', title: 'New Work Chicago', institution: 'Museum of Contemporary Art Chicago, IL', year: 2024, sortOrder: 4 },
    { type: 'residency', title: 'BOLT Residency', institution: 'Chicago Artists Coalition, Chicago, IL', year: 2024, sortOrder: 5 },
    { type: 'award', title: 'SAIC Fellowship', institution: 'School of the Art Institute of Chicago, IL', year: 2023, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Hanok Window, Morning',
      description: 'Acrylic and hanji (Korean mulberry paper) on cradled panel. The translucent paper creates a soft, backlit quality reminiscent of the papered windows of traditional Korean houses. Pale washes of blue and grey suggest early morning light.',
      medium: 'acrylic and hanji on cradled panel',
      category: 'painting',
      price: 22000,
      status: 'available',
      isDocumented: true,
      artworkLength: 18, artworkWidth: 24, artworkHeight: 1.5,
      packedLength: 22, packedWidth: 28, packedHeight: 5,
      packedWeight: 5,
    },
    {
      title: 'Moon Jar, celadon',
      description: 'Hand-thrown porcelain moon jar with celadon glaze. The traditional Korean form is slightly asymmetrical, reflecting the artist\'s embrace of imperfection. Functional as a vase or beautiful as a standalone sculptural object.',
      medium: 'porcelain, celadon glaze',
      category: 'ceramics',
      price: 18000,
      status: 'available',
      isDocumented: true,
      artworkLength: 8, artworkWidth: 8, artworkHeight: 10,
      packedLength: 12, packedWidth: 12, packedHeight: 14,
      packedWeight: 5,
    },
    {
      title: 'Grid Study No. 12',
      description: 'Small acrylic painting on panel exploring the grid as a meeting point between the urban grid of Chicago and the woven patterns of Korean bojagi wrapping cloths. Muted palette of warm greys and soft pinks.',
      medium: 'acrylic on panel',
      category: 'painting',
      price: 12000,
      status: 'available',
      isDocumented: false,
      artworkLength: 10, artworkWidth: 10, artworkHeight: 1,
      packedLength: 14, packedWidth: 14, packedHeight: 4,
      packedWeight: 2,
    },
    {
      title: 'Tea Cup Set, white',
      description: 'Set of four hand-thrown porcelain tea cups with a translucent white glaze. Each cup is slightly different in height and diameter, following the Korean aesthetic of intentional variation within a set.',
      medium: 'porcelain, white glaze',
      category: 'ceramics',
      price: 8500,
      status: 'available',
      isDocumented: false,
      artworkLength: 3.5, artworkWidth: 3.5, artworkHeight: 3,
      packedLength: 12, packedWidth: 12, packedHeight: 7,
      packedWeight: 3,
    },
    {
      title: 'Bojagi Fragment',
      description: 'Acrylic and hanji on panel inspired by the translucent patchwork of Korean bojagi textiles. Overlapping rectangles of color create a luminous, stained-glass quality.',
      medium: 'acrylic and hanji on panel',
      category: 'painting',
      price: 16000,
      status: 'sold',
      isDocumented: false,
      artworkLength: 14, artworkWidth: 18, artworkHeight: 1.5,
      packedLength: 18, packedWidth: 22, packedHeight: 5,
      packedWeight: 4,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('sunhi-park', 'process/studio')), sortOrder: 0 },
  ],
}

export const paintingArtists: ArtistSeedConfig[] = [
  elenaConfig,
  jamesConfig,
  priyaConfig,
  sunhiConfig,
]
