import type { ArtistSeedConfig } from '../types'
import { cdnUrl, seedKey } from '../cdn'

// ============================================================================
// Jordan Blackwood — Austin, TX — photography, mixed_media — Emerging (30s)
// ============================================================================

const jordanConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-jordan-blackwood-cognito',
    email: 'jordan@jordanblackwoodphoto.com',
    fullName: 'Jordan Blackwood',
    avatarUrl: cdnUrl(seedKey('jordan-blackwood', 'profile')),
  },
  profile: {
    displayName: 'Jordan Blackwood',
    slug: 'jordan-blackwood',
    bio: 'Jordan Blackwood is a mixed-race photographer and mixed media artist based in Austin, Texas. Their work explores the constructed nature of identity through staged portraiture, found object assemblage, and archival intervention. Using a large-format film camera alongside digital processes, Blackwood creates images that oscillate between documentary and fiction. They hold an MFA from the University of Texas at Austin and a BA from Bard College. Their photographs have been exhibited at Artpace San Antonio, the Contemporary Austin, and the Houston Center for Photography. Blackwood is a founding member of Third Space Collective, a BIPOC and queer artist cooperative in East Austin.',
    location: 'Austin, TX',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '78702',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('jordan-blackwood', 'cover')),
    profileImageUrl: cdnUrl(seedKey('jordan-blackwood', 'profile')),
    applicationSource: 'direct_application',
    isDemo: true,
  },
  categories: ['photography', 'mixed_media'],
  cvEntries: [
    { type: 'education', title: 'MFA, Studio Art (Photography)', institution: 'University of Texas at Austin, TX', year: 2020, sortOrder: 1 },
    { type: 'education', title: 'BA, Photography', institution: 'Bard College, Annandale-on-Hudson, NY', year: 2016, sortOrder: 2 },
    { type: 'exhibition', title: 'Third Space', institution: 'Artpace San Antonio, San Antonio, TX', year: 2025, sortOrder: 3 },
    { type: 'exhibition', title: 'New Photography', institution: 'Contemporary Austin, Austin, TX', year: 2023, sortOrder: 4 },
    { type: 'residency', title: 'Artist in Residence', institution: 'Light Work, Syracuse, NY', year: 2022, sortOrder: 5 },
    { type: 'award', title: 'Artpace International Artist Residency', institution: 'Artpace, San Antonio, TX', year: 2025, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Self-Portrait with Archive',
      description: 'Archival pigment print of a staged self-portrait in which the artist is surrounded by family photographs, documents, and objects from multiple cultural traditions. The large-format film negative captures every detail with crystalline sharpness. Printed on Hahnemühle Photo Rag.',
      medium: 'archival pigment print, edition of 10',
      category: 'photography',
      price: 32000,
      status: 'available',
      isDocumented: true,
      artworkLength: 30, artworkWidth: 40, artworkHeight: 0,
      packedLength: 34, packedWidth: 44, packedHeight: 4,
      packedWeight: 3,
    },
    {
      title: 'East Side Story No. 3',
      description: 'Documentary photograph from an ongoing series about East Austin\'s transformation. A portrait of a longtime resident on their front porch, framed by new construction in the background. Printed on baryta paper with rich, warm tones.',
      medium: 'archival pigment print on baryta, edition of 15',
      category: 'photography',
      price: 18000,
      status: 'available',
      isDocumented: false,
      artworkLength: 20, artworkWidth: 24, artworkHeight: 0,
      packedLength: 24, packedWidth: 28, packedHeight: 3,
      packedWeight: 2,
    },
    {
      title: 'Object Lesson (Family Bible)',
      description: 'Mixed media piece combining an archival pigment print of a well-worn family Bible with pressed botanical specimens and handwritten annotations. The photograph and physical objects are layered in a shadowbox frame, blurring the boundary between image and artifact.',
      medium: 'archival print, pressed botanicals, shadowbox',
      category: 'mixed_media',
      price: 28000,
      status: 'available',
      isDocumented: true,
      artworkLength: 16, artworkWidth: 20, artworkHeight: 3,
      packedLength: 20, packedWidth: 24, packedHeight: 7,
      packedWeight: 6,
    },
    {
      title: 'Barton Springs, August',
      description: 'Color photograph of swimmers at Barton Springs Pool on a hot August afternoon. Shot on medium-format film with saturated color and a wide perspective that captures the full sweep of the spring-fed pool against the Austin skyline.',
      medium: 'archival pigment print, edition of 20',
      category: 'photography',
      price: 12000,
      status: 'available',
      isDocumented: false,
      artworkLength: 16, artworkWidth: 24, artworkHeight: 0,
      packedLength: 20, packedWidth: 28, packedHeight: 3,
      packedWeight: 1.5,
    },
    {
      title: 'Untitled (Grandmother\'s Hands)',
      description: 'Intimate portrait of the artist\'s grandmother\'s hands holding a photograph of herself as a young woman. Shot on 4x5 large-format film. The shallow depth of field draws attention to the textured skin and the small faded photograph.',
      medium: 'archival pigment print, edition of 8',
      category: 'photography',
      price: 38000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 24, artworkWidth: 30, artworkHeight: 0,
      packedLength: 28, packedWidth: 34, packedHeight: 4,
      packedWeight: 2.5,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('jordan-blackwood', 'process/studio')), sortOrder: 0 },
  ],
}

// ============================================================================
// Tomoko Ishida — Seattle, WA — photography, ceramics — Established (50s)
// ============================================================================

const tomokoConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-tomoko-ishida-cognito',
    email: 'tomoko@tomokoishida.com',
    fullName: 'Tomoko Ishida',
    avatarUrl: cdnUrl(seedKey('tomoko-ishida', 'profile')),
  },
  profile: {
    displayName: 'Tomoko Ishida',
    slug: 'tomoko-ishida',
    bio: 'Tomoko Ishida is a Japanese photographer and ceramicist based in Seattle, Washington. For over two decades, her practice has moved between the camera and the kiln, finding common ground in the contemplation of light, surface, and impermanence. Her silver gelatin prints, developed by hand in her darkroom, document the landscapes and still lifes of the Pacific Northwest with a quietness rooted in the Japanese aesthetic of wabi-sabi. Her ceramic work — small, unglazed stoneware vessels — often appears as subjects in her photographs. Ishida holds an MFA from the University of Washington and studied photography at Tokyo Zokei University. Her work is in the collections of the Seattle Art Museum, the Portland Art Museum, and the Tacoma Art Museum.',
    location: 'Seattle, WA',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '98101',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('tomoko-ishida', 'cover')),
    profileImageUrl: cdnUrl(seedKey('tomoko-ishida', 'profile')),
    applicationSource: 'advisor_network',
    isDemo: true,
  },
  categories: ['photography', 'ceramics'],
  cvEntries: [
    { type: 'education', title: 'MFA, Photography', institution: 'University of Washington, Seattle, WA', year: 2002, sortOrder: 1 },
    { type: 'education', title: 'BA, Photography', institution: 'Tokyo Zokei University, Tokyo, Japan', year: 1997, sortOrder: 2 },
    { type: 'exhibition', title: 'Quiet Light', institution: 'Seattle Art Museum, Seattle, WA', year: 2024, sortOrder: 3 },
    { type: 'exhibition', title: 'Still Life with Vessel', institution: 'Portland Art Museum, Portland, OR', year: 2021, sortOrder: 4 },
    { type: 'residency', title: 'Artist in Residence', institution: 'Haystack Mountain School of Crafts, Deer Isle, ME', year: 2015, sortOrder: 5 },
    { type: 'award', title: 'Artist Trust Fellowship', institution: 'Artist Trust, Seattle, WA', year: 2022, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Rain on Glass, Puget Sound',
      description: 'Silver gelatin print of rain running down a window with Puget Sound visible through the droplets. Hand-printed in the artist\'s darkroom on fiber-based paper with selenium toning for archival permanence. The tonal range captures every nuance of the grey Pacific Northwest light.',
      medium: 'silver gelatin print, edition of 10',
      category: 'photography',
      price: 38000,
      status: 'available',
      isDocumented: true,
      artworkLength: 16, artworkWidth: 20, artworkHeight: 0,
      packedLength: 20, packedWidth: 24, packedHeight: 3,
      packedWeight: 2,
    },
    {
      title: 'Three Vessels',
      description: 'Silver gelatin photograph of three of the artist\'s own unglazed stoneware vessels arranged on a wooden shelf, lit by a single north-facing window. The photograph explores the relationship between photographic surface and ceramic surface. Hand-printed with split toning.',
      medium: 'silver gelatin print, edition of 12',
      category: 'photography',
      price: 28000,
      status: 'available',
      isDocumented: false,
      artworkLength: 14, artworkWidth: 14, artworkHeight: 0,
      packedLength: 18, packedWidth: 18, packedHeight: 3,
      packedWeight: 1.5,
    },
    {
      title: 'Chawan, ash glaze',
      description: 'Hand-thrown stoneware tea bowl with a natural wood ash glaze. The bowl was fired in the artist\'s wood-fired kiln over three days. The ash glaze creates unpredictable patterns of color and texture that embody the wabi-sabi aesthetic of beautiful imperfection.',
      medium: 'stoneware, wood ash glaze',
      category: 'ceramics',
      price: 15000,
      status: 'available',
      isDocumented: true,
      artworkLength: 5, artworkWidth: 5, artworkHeight: 3.5,
      packedLength: 9, packedWidth: 9, packedHeight: 7.5,
      packedWeight: 2,
    },
    {
      title: 'Moss and Stone',
      description: 'Silver gelatin print of moss growing on a basalt boulder along the Hoh River in Olympic National Park. The extreme close-up perspective transforms the moss into an abstract landscape. Hand-printed on warm-tone fiber paper.',
      medium: 'silver gelatin print, edition of 15',
      category: 'photography',
      price: 18000,
      status: 'available',
      isDocumented: false,
      artworkLength: 12, artworkWidth: 16, artworkHeight: 0,
      packedLength: 16, packedWidth: 20, packedHeight: 3,
      packedWeight: 1.5,
    },
    {
      title: 'Winter Light, Studio',
      description: 'Intimate photograph of the artist\'s studio in winter, with low afternoon light raking across shelves of unfired vessels. The long exposure renders the slowly shifting light as a soft, luminous haze. Selenium-toned silver gelatin.',
      medium: 'silver gelatin print, edition of 8',
      category: 'photography',
      price: 42000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 20, artworkWidth: 24, artworkHeight: 0,
      packedLength: 24, packedWidth: 28, packedHeight: 4,
      packedWeight: 2,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('tomoko-ishida', 'process/studio')), sortOrder: 0 },
  ],
}

// ============================================================================
// Gabriela Santos — Miami, FL — photography, painting — Emerging (20s)
// ============================================================================

const gabrielaConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-gabriela-santos-cognito',
    email: 'gabriela@gabrielasantosphoto.com',
    fullName: 'Gabriela Santos',
    avatarUrl: cdnUrl(seedKey('gabriela-santos', 'profile')),
  },
  profile: {
    displayName: 'Gabriela Santos',
    slug: 'gabriela-santos',
    bio: 'Gabriela Santos is a Brazilian-American photographer and painter based in Miami, Florida. Her vibrant color photographs and hand-painted photographic prints explore the visual culture of Miami\'s Caribbean and Latin American diaspora communities. Santos shoots on medium-format film, drawn to the saturated colors and graphic compositions of street life, architecture, and seasonal celebrations. She holds an MFA from the University of Miami and a BFA from Florida International University. Her work has been exhibited at the Pérez Art Museum Miami, the Museum of Contemporary Art North Miami, and the Frost Art Museum. She is a 2024 Oolite Arts resident.',
    location: 'Miami, FL',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '33130',
    status: 'approved',
    commissionsOpen: true,
    coverImageUrl: cdnUrl(seedKey('gabriela-santos', 'cover')),
    profileImageUrl: cdnUrl(seedKey('gabriela-santos', 'profile')),
    applicationSource: 'direct_application',
    isDemo: true,
  },
  categories: ['photography', 'painting'],
  cvEntries: [
    { type: 'education', title: 'MFA, Photography', institution: 'University of Miami, Coral Gables, FL', year: 2023, sortOrder: 1 },
    { type: 'education', title: 'BFA, Art', institution: 'Florida International University, Miami, FL', year: 2020, sortOrder: 2 },
    { type: 'exhibition', title: 'Tropical Modern', institution: 'Pérez Art Museum Miami, Miami, FL', year: 2025, sortOrder: 3 },
    { type: 'exhibition', title: 'Young Photographers', institution: 'Museum of Contemporary Art North Miami, FL', year: 2024, sortOrder: 4 },
    { type: 'residency', title: 'Artist in Residence', institution: 'Oolite Arts, Miami Beach, FL', year: 2024, sortOrder: 5 },
    { type: 'award', title: 'South Florida Cultural Consortium Fellowship', institution: 'Miami-Dade County, FL', year: 2025, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Little Havana, Calle Ocho',
      description: 'Color photograph of the Calle Ocho streetscape shot on medium-format Portra film. The late afternoon light catches the painted facades of domino parks and ventanitas, creating a warm, nostalgic palette of coral, turquoise, and gold.',
      medium: 'archival pigment print, edition of 15',
      category: 'photography',
      price: 14000,
      status: 'available',
      isDocumented: true,
      artworkLength: 20, artworkWidth: 24, artworkHeight: 0,
      packedLength: 24, packedWidth: 28, packedHeight: 3,
      packedWeight: 2,
    },
    {
      title: 'Carnaval, Wynwood',
      description: 'Dynamic photograph of dancers at the Carnaval on the Mile festival. The motion blur of spinning costumes against sharp architectural backgrounds creates a tension between movement and stillness. Vibrant color print on metallic paper.',
      medium: 'archival pigment print on metallic, edition of 20',
      category: 'photography',
      price: 10000,
      status: 'available',
      isDocumented: false,
      artworkLength: 16, artworkWidth: 20, artworkHeight: 0,
      packedLength: 20, packedWidth: 24, packedHeight: 3,
      packedWeight: 1.5,
    },
    {
      title: 'Biscayne Bay, Pink Hour',
      description: 'Large-format photograph of Biscayne Bay at the brief moment when the sky turns pink before sunset. Shot on medium-format slide film for maximum color saturation. The water reflects the sky in subtle gradations of pink, lavender, and gold.',
      medium: 'archival pigment print, edition of 10',
      category: 'photography',
      price: 22000,
      status: 'available',
      isDocumented: true,
      artworkLength: 24, artworkWidth: 36, artworkHeight: 0,
      packedLength: 28, packedWidth: 40, packedHeight: 4,
      packedWeight: 2.5,
    },
    {
      title: 'Fruit Stand, Homestead',
      description: 'Close-up color photograph of a roadside fruit stand in Homestead, piled with tropical fruit — mamey, guanabana, starfruit, and mangoes. The colors and textures create an almost painterly composition. C-print on glossy paper.',
      medium: 'C-print, edition of 25',
      category: 'photography',
      price: 8000,
      status: 'available',
      isDocumented: false,
      artworkLength: 14, artworkWidth: 18, artworkHeight: 0,
      packedLength: 18, packedWidth: 22, packedHeight: 2,
      packedWeight: 1,
    },
    {
      title: 'Abuela\'s Garden',
      description: 'Intimate photograph of the artist\'s grandmother\'s backyard garden in Hialeah, dense with tropical plants, santos figurines, and hanging laundry. The composition is a visual inventory of diasporic domesticity, tender and specific.',
      medium: 'archival pigment print, edition of 10',
      category: 'photography',
      price: 18000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 20, artworkWidth: 24, artworkHeight: 0,
      packedLength: 24, packedWidth: 28, packedHeight: 3,
      packedWeight: 2,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('gabriela-santos', 'process/studio')), sortOrder: 0 },
  ],
}

// ============================================================================
// Aiden McAllister — Asheville, NC — photography, fibers — Emerging (30s)
// ============================================================================

const aidenConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-aiden-mcallister-cognito',
    email: 'aiden@aidenmcallisterphoto.com',
    fullName: 'Aiden McAllister',
    avatarUrl: cdnUrl(seedKey('aiden-mcallister', 'profile')),
  },
  profile: {
    displayName: 'Aiden McAllister',
    slug: 'aiden-mcallister',
    bio: 'Aiden McAllister is an Irish-American photographer and fiber artist based in Asheville, North Carolina. His work documents the Appalachian craft tradition through both lens-based media and his own hand-woven textiles. McAllister photographs the studios, tools, and processes of traditional craftspeople across western North Carolina, creating an archival record of knowledge systems at risk of disappearing. His own weaving practice, learned from weavers he photographs, produces functional textiles that connect his documentary work to the lived experience of craft. He holds an MFA from Appalachian State University and a BA from the University of North Carolina at Asheville.',
    location: 'Asheville, NC',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '28801',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('aiden-mcallister', 'cover')),
    profileImageUrl: cdnUrl(seedKey('aiden-mcallister', 'profile')),
    applicationSource: 'direct_application',
    isDemo: true,
  },
  categories: ['photography', 'fibers'],
  cvEntries: [
    { type: 'education', title: 'MFA, Studio Art', institution: 'Appalachian State University, Boone, NC', year: 2021, sortOrder: 1 },
    { type: 'education', title: 'BA, Art', institution: 'University of North Carolina at Asheville, NC', year: 2017, sortOrder: 2 },
    { type: 'exhibition', title: 'Craft Portraits', institution: 'Asheville Art Museum, Asheville, NC', year: 2025, sortOrder: 3 },
    { type: 'exhibition', title: 'Appalachian Futures', institution: 'Center for Craft, Asheville, NC', year: 2023, sortOrder: 4 },
    { type: 'residency', title: 'Craft Research Fellowship', institution: 'Penland School of Craft, Bakersville, NC', year: 2022, sortOrder: 5 },
    { type: 'award', title: 'North Carolina Arts Council Fellowship', institution: 'Raleigh, NC', year: 2024, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Weaver\'s Hands, Cherokee',
      description: 'Black and white photograph of a Cherokee basket weaver\'s hands selecting river cane strips. Shot on medium-format film and hand-printed as a silver gelatin print. The close-up perspective honors the knowledge held in these hands. Printed with archival selenium toning.',
      medium: 'silver gelatin print, edition of 12',
      category: 'photography',
      price: 22000,
      status: 'available',
      isDocumented: true,
      artworkLength: 16, artworkWidth: 20, artworkHeight: 0,
      packedLength: 20, packedWidth: 24, packedHeight: 3,
      packedWeight: 1.5,
    },
    {
      title: 'Cabin Blanket, Indigo and Walnut',
      description: 'Hand-woven wool blanket dyed with natural indigo and black walnut hull. The simple twill pattern is traditional to southern Appalachian coverlet weaving. Woven on a four-harness floor loom from locally sourced wool.',
      medium: 'hand-woven wool, natural dyes',
      category: 'fibers',
      price: 35000,
      status: 'available',
      isDocumented: true,
      artworkLength: 60, artworkWidth: 80, artworkHeight: 1,
      packedLength: 16, packedWidth: 12, packedHeight: 8,
      packedWeight: 5,
    },
    {
      title: 'Blacksmith\'s Forge, Spruce Pine',
      description: 'Color photograph of a blacksmith\'s forge in Spruce Pine, North Carolina. The orange glow of the forge illuminates the tools hanging on the wall and the smith\'s silhouette. Shot on large-format 4x5 film for maximum detail.',
      medium: 'archival pigment print, edition of 15',
      category: 'photography',
      price: 16000,
      status: 'available',
      isDocumented: false,
      artworkLength: 16, artworkWidth: 20, artworkHeight: 0,
      packedLength: 20, packedWidth: 24, packedHeight: 3,
      packedWeight: 1.5,
    },
    {
      title: 'Woven Scarf, Madder and Marigold',
      description: 'Lightweight hand-woven scarf in fine merino wool dyed with madder root (coral) and marigold (golden yellow). The plain weave allows the natural dye colors to blend where the warp and weft cross. Finished with hand-twisted fringe.',
      medium: 'hand-woven merino wool, natural dyes',
      category: 'fibers',
      price: 8500,
      status: 'available',
      isDocumented: false,
      artworkLength: 60, artworkWidth: 10, artworkHeight: 0.25,
      packedLength: 12, packedWidth: 8, packedHeight: 4,
      packedWeight: 0.5,
    },
    {
      title: 'Potter\'s Wheel, Seagrove',
      description: 'Environmental portrait of a fourth-generation potter at the wheel in Seagrove, North Carolina, the historic pottery capital of the South. Shot on black and white medium-format film with natural light from the studio\'s north-facing windows.',
      medium: 'silver gelatin print, edition of 10',
      category: 'photography',
      price: 24000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 20, artworkWidth: 24, artworkHeight: 0,
      packedLength: 24, packedWidth: 28, packedHeight: 3,
      packedWeight: 2,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('aiden-mcallister', 'process/studio')), sortOrder: 0 },
  ],
}

export const photographyArtists: ArtistSeedConfig[] = [
  jordanConfig,
  tomokoConfig,
  gabrielaConfig,
  aidenConfig,
]
