import type { ArtistSeedConfig } from '../types'
import { cdnUrl, seedKey } from '../cdn'

// ============================================================================
// Ren Takahashi — San Francisco, CA — print, illustration — Emerging (30s)
// ============================================================================

const renConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-ren-takahashi-cognito',
    email: 'ren@rentakahashi.com',
    fullName: 'Ren Takahashi',
    avatarUrl: cdnUrl(seedKey('ren-takahashi', 'profile')),
  },
  profile: {
    displayName: 'Ren Takahashi',
    slug: 'ren-takahashi',
    bio: 'Ren Takahashi is a Japanese-American printmaker and illustrator based in San Francisco. Working primarily in risograph and screenprint, Takahashi creates bold, graphic compositions that explore queer identity, urban ecology, and the visual language of zine culture. Their work combines hand-drawn illustration with digital collage, printed in small editions on recycled paper stocks. Takahashi holds an MFA from California College of the Arts and a BA from UC Berkeley. Their prints have been exhibited at the San Francisco Center for the Book, Printed Matter in New York, and the International Print Center. They are a co-founder of Tidal Press, a community printshop in the Mission District.',
    location: 'San Francisco, CA',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '94110',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('ren-takahashi', 'cover')),
    profileImageUrl: cdnUrl(seedKey('ren-takahashi', 'profile')),
    applicationSource: 'direct_application',
    isDemo: true,
  },
  categories: ['print', 'illustration'],
  cvEntries: [
    { type: 'education', title: 'MFA, Printmaking', institution: 'California College of the Arts, San Francisco, CA', year: 2020, sortOrder: 1 },
    { type: 'education', title: 'BA, Art Practice', institution: 'UC Berkeley, Berkeley, CA', year: 2016, sortOrder: 2 },
    { type: 'exhibition', title: 'Layered City', institution: 'San Francisco Center for the Book, San Francisco, CA', year: 2025, sortOrder: 3 },
    { type: 'exhibition', title: 'Riso Revolution', institution: 'Printed Matter, New York, NY', year: 2023, sortOrder: 4 },
    { type: 'residency', title: 'Print Fellow', institution: 'Kala Art Institute, Berkeley, CA', year: 2021, sortOrder: 5 },
    { type: 'award', title: 'Emerging Printmaker Award', institution: 'Southern Graphics Council International', year: 2022, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Fog City Layers',
      description: 'Four-color risograph print depicting the layered architecture of San Francisco seen through morning fog. Hand-drawn linework printed in fluorescent pink, blue, yellow, and black on recycled French Paper. Edition of fifty, signed and numbered.',
      medium: 'risograph on recycled paper, edition of 50',
      category: 'print',
      price: 4500,
      status: 'available',
      isDocumented: true,
      artworkLength: 11, artworkWidth: 17, artworkHeight: 0,
      packedLength: 15, packedWidth: 21, packedHeight: 2,
      packedWeight: 0.5,
    },
    {
      title: 'Urban Pollinator',
      description: 'Three-color screenprint of a hummingbird navigating between rooftop gardens and fire escapes. Bold graphic forms and a limited palette of emerald, coral, and cream. Printed on heavyweight cotton rag. Edition of thirty.',
      medium: 'screenprint on cotton rag, edition of 30',
      category: 'print',
      price: 8000,
      status: 'available',
      isDocumented: false,
      artworkLength: 18, artworkWidth: 24, artworkHeight: 0,
      packedLength: 22, packedWidth: 28, packedHeight: 2,
      packedWeight: 1,
    },
    {
      title: 'Transit Map (Queer Atlas)',
      description: 'Two-color risograph print reimagining the Bay Area transit map as a network of queer community spaces, past and present. Printed in soy-based ink on Japanese newsprint. Edition of seventy-five.',
      medium: 'risograph on newsprint, edition of 75',
      category: 'print',
      price: 4500,
      status: 'available',
      isDocumented: false,
      artworkLength: 11, artworkWidth: 17, artworkHeight: 0,
      packedLength: 15, packedWidth: 21, packedHeight: 2,
      packedWeight: 0.5,
    },
    {
      title: 'Night Garden',
      description: 'Hand-drawn ink illustration of a nighttime community garden teeming with nocturnal insects and glowing fungi. Original drawing in archival ink on hot-pressed watercolor paper. One of a kind.',
      medium: 'archival ink on paper',
      category: 'illustration',
      price: 12000,
      status: 'available',
      isDocumented: true,
      artworkLength: 14, artworkWidth: 18, artworkHeight: 0,
      packedLength: 18, packedWidth: 22, packedHeight: 3,
      packedWeight: 1,
    },
    {
      title: 'Solstice',
      description: 'Five-color screenprint celebrating the summer solstice with overlapping botanical forms and celestial geometry. The most complex registration piece from the Seasonal Cycle series. Edition of twenty.',
      medium: 'screenprint on cotton rag, edition of 20',
      category: 'print',
      price: 14000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 22, artworkWidth: 30, artworkHeight: 0,
      packedLength: 26, packedWidth: 34, packedHeight: 3,
      packedWeight: 1.5,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('ren-takahashi', 'process/studio')), sortOrder: 0 },
  ],
}

// ============================================================================
// Desiree LaFleur — New Orleans, LA — print, illustration — Mid-career (40s)
// ============================================================================

const desireeConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-desiree-lafleur-cognito',
    email: 'desiree@desireelafleur.com',
    fullName: 'Desiree LaFleur',
    avatarUrl: cdnUrl(seedKey('desiree-lafleur', 'profile')),
  },
  profile: {
    displayName: 'Desiree LaFleur',
    slug: 'desiree-lafleur',
    bio: 'Desiree LaFleur is a Black Creole printmaker and illustrator based in New Orleans. Her linocut and letterpress prints celebrate the visual culture of Louisiana — from Mardi Gras Indian suits to shotgun house architecture to the hand-painted signage of neighborhood po\'boy shops. LaFleur holds an MFA from Tulane University and a BFA from Xavier University of Louisiana. She has exhibited at the Ogden Museum of Southern Art, the New Orleans Museum of Art, and Prospect New Orleans. Her work is in the permanent collections of the Amistad Research Center and the Historic New Orleans Collection. She runs Bayou Press, a letterpress studio in the Bywater neighborhood.',
    location: 'New Orleans, LA',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '70116',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('desiree-lafleur', 'cover')),
    profileImageUrl: cdnUrl(seedKey('desiree-lafleur', 'profile')),
    applicationSource: 'advisor_network',
    isDemo: true,
  },
  categories: ['print', 'illustration'],
  cvEntries: [
    { type: 'education', title: 'MFA, Printmaking', institution: 'Tulane University, New Orleans, LA', year: 2010, sortOrder: 1 },
    { type: 'education', title: 'BFA, Fine Arts', institution: 'Xavier University of Louisiana, New Orleans, LA', year: 2006, sortOrder: 2 },
    { type: 'exhibition', title: 'Carnival Lines', institution: 'Ogden Museum of Southern Art, New Orleans, LA', year: 2025, sortOrder: 3 },
    { type: 'exhibition', title: 'Southern Impressions', institution: 'New Orleans Museum of Art, New Orleans, LA', year: 2022, sortOrder: 4 },
    { type: 'residency', title: 'Printmaking Fellow', institution: 'Penland School of Craft, Bakersville, NC', year: 2018, sortOrder: 5 },
    { type: 'award', title: 'Louisiana Division of the Arts Fellowship', institution: 'Baton Rouge, LA', year: 2021, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Shotgun House, Tremé',
      description: 'Hand-carved linocut print depicting the iconic shotgun house form of the Tremé neighborhood. Printed in a single color of deep indigo on cream Rives BFK. The carved linoleum block captures the decorative millwork and iron railings characteristic of the neighborhood.',
      medium: 'linocut on Rives BFK, edition of 20',
      category: 'print',
      price: 9500,
      status: 'available',
      isDocumented: true,
      artworkLength: 14, artworkWidth: 20, artworkHeight: 0,
      packedLength: 18, packedWidth: 24, packedHeight: 2,
      packedWeight: 1,
    },
    {
      title: 'Second Line',
      description: 'Multi-color linocut of a second line parade moving through the Seventh Ward. Printed in four colors using a reduction process — each color carved and printed from the same block. Edition of fifteen.',
      medium: 'reduction linocut on cotton rag, edition of 15',
      category: 'print',
      price: 15000,
      status: 'available',
      isDocumented: true,
      artworkLength: 18, artworkWidth: 24, artworkHeight: 0,
      packedLength: 22, packedWidth: 28, packedHeight: 2,
      packedWeight: 1,
    },
    {
      title: 'Po-Boy Sign, Magazine Street',
      description: 'Letterpress print reproducing the hand-painted sign lettering of a beloved Magazine Street po\'boy shop. Printed on a vintage Vandercook press using wood type and hand-set metal type. Each print has slight ink variations unique to the letterpress process.',
      medium: 'letterpress on French Paper, edition of 40',
      category: 'print',
      price: 5500,
      status: 'available',
      isDocumented: false,
      artworkLength: 11, artworkWidth: 14, artworkHeight: 0,
      packedLength: 15, packedWidth: 18, packedHeight: 2,
      packedWeight: 0.5,
    },
    {
      title: 'Magnolia & Mosquito',
      description: 'Original pen and ink illustration of a magnolia blossom with a mosquito perched on one petal. A wry tribute to the beauty and nuisance of Louisiana summers. Drawn with Micron pens on hot-pressed watercolor paper.',
      medium: 'ink on paper',
      category: 'illustration',
      price: 8000,
      status: 'available',
      isDocumented: false,
      artworkLength: 9, artworkWidth: 12, artworkHeight: 0,
      packedLength: 13, packedWidth: 16, packedHeight: 2,
      packedWeight: 0.5,
    },
    {
      title: 'Mardi Gras Indian, Big Chief',
      description: 'Large-format reduction linocut of a Mardi Gras Indian Big Chief in full regalia. Six colors printed from a single block in a week-long printing marathon. The most labor-intensive print in the Carnival Lines series.',
      medium: 'reduction linocut on cotton rag, edition of 10',
      category: 'print',
      price: 18000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 24, artworkWidth: 30, artworkHeight: 0,
      packedLength: 28, packedWidth: 34, packedHeight: 3,
      packedWeight: 2,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('desiree-lafleur', 'process/studio')), sortOrder: 0 },
  ],
}

// ============================================================================
// Nathan Clearwater — Flagstaff, AZ — print, woodworking — Emerging (30s)
// ============================================================================

const nathanConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-nathan-clearwater-cognito',
    email: 'nathan@nathanclearwater.com',
    fullName: 'Nathan Clearwater',
    avatarUrl: cdnUrl(seedKey('nathan-clearwater', 'profile')),
  },
  profile: {
    displayName: 'Nathan Clearwater',
    slug: 'nathan-clearwater',
    bio: 'Nathan Clearwater is a Diné (Navajo) printmaker and woodworker based in Flagstaff, Arizona. His woodcut prints and carved objects draw from the visual traditions of Navajo weaving, sandpainting, and the landscape of the Colorado Plateau. Clearwater carves his printing blocks from locally sourced ponderosa pine, connecting the material of the print matrix to the land his work depicts. He holds an MFA from Arizona State University and a BFA from the Institute of American Indian Arts. His prints have been exhibited at the Heard Museum, the Museum of Northern Arizona, and the SWAIA Indian Market. He teaches printmaking at Coconino Community College.',
    location: 'Flagstaff, AZ',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '86001',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('nathan-clearwater', 'cover')),
    profileImageUrl: cdnUrl(seedKey('nathan-clearwater', 'profile')),
    applicationSource: 'direct_application',
    isDemo: true,
  },
  categories: ['print', 'woodworking'],
  cvEntries: [
    { type: 'education', title: 'MFA, Printmaking', institution: 'Arizona State University, Tempe, AZ', year: 2020, sortOrder: 1 },
    { type: 'education', title: 'BFA, Studio Arts', institution: 'Institute of American Indian Arts, Santa Fe, NM', year: 2016, sortOrder: 2 },
    { type: 'exhibition', title: 'Plateau Impressions', institution: 'Museum of Northern Arizona, Flagstaff, AZ', year: 2025, sortOrder: 3 },
    { type: 'exhibition', title: 'New Prints', institution: 'Heard Museum, Phoenix, AZ', year: 2023, sortOrder: 4 },
    { type: 'award', title: 'Best of Classification, Printmaking', institution: 'SWAIA Santa Fe Indian Market', year: 2024, sortOrder: 5 },
  ],
  listings: [
    {
      title: 'Canyon Walls, Tsegi',
      description: 'Large-format woodcut print carved from ponderosa pine and printed on handmade mulberry paper. The image depicts the striated canyon walls of Tsegi Canyon. Printed in a single pull of burnt umber ink. Edition of twelve.',
      medium: 'woodcut on mulberry paper, edition of 12',
      category: 'print',
      price: 14000,
      status: 'available',
      isDocumented: true,
      artworkLength: 22, artworkWidth: 30, artworkHeight: 0,
      packedLength: 26, packedWidth: 34, packedHeight: 3,
      packedWeight: 1.5,
    },
    {
      title: 'Storm Pattern',
      description: 'Woodcut print inspired by the storm pattern of traditional Navajo textiles. Geometric forms radiate from a central diamond, printed in black sumi ink on natural kozo paper. The grain of the pine block becomes part of the image.',
      medium: 'woodcut on kozo paper, edition of 20',
      category: 'print',
      price: 8500,
      status: 'available',
      isDocumented: false,
      artworkLength: 16, artworkWidth: 20, artworkHeight: 0,
      packedLength: 20, packedWidth: 24, packedHeight: 2,
      packedWeight: 1,
    },
    {
      title: 'Carved Bowl, Juniper',
      description: 'Hand-carved bowl from reclaimed juniper wood. The natural grain and aromatic quality of the wood are preserved through a food-safe oil finish. The form references traditional Pueblo seed jars translated into wood.',
      medium: 'hand-carved juniper, oil finish',
      category: 'woodworking',
      price: 16000,
      status: 'available',
      isDocumented: true,
      artworkLength: 8, artworkWidth: 8, artworkHeight: 4,
      packedLength: 12, packedWidth: 12, packedHeight: 8,
      packedWeight: 3,
    },
    {
      title: 'Ponderosa Series No. 5',
      description: 'Small woodcut print from the Ponderosa Series — an ongoing project documenting the bark patterns and growth rings of ponderosa pines on the Coconino Plateau. Printed in sepia ink on cream washi.',
      medium: 'woodcut on washi, edition of 25',
      category: 'print',
      price: 4800,
      status: 'available',
      isDocumented: false,
      artworkLength: 8, artworkWidth: 10, artworkHeight: 0,
      packedLength: 12, packedWidth: 14, packedHeight: 2,
      packedWeight: 0.5,
    },
    {
      title: 'Four Sacred Mountains',
      description: 'Panoramic woodcut depicting the four sacred mountains of the Navajo homeland. Carved from a single long plank of pine, printed as a continuous landscape in dark indigo on handmade paper.',
      medium: 'woodcut on handmade paper, edition of 8',
      category: 'print',
      price: 18000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 12, artworkWidth: 36, artworkHeight: 0,
      packedLength: 16, packedWidth: 40, packedHeight: 3,
      packedWeight: 2,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('nathan-clearwater', 'process/studio')), sortOrder: 0 },
  ],
}

// ============================================================================
// Caleb Johannsen — Minneapolis, MN — print, woodworking — Established (50s)
// ============================================================================

const calebConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-caleb-johannsen-cognito',
    email: 'caleb@calebjohannsenstudio.com',
    fullName: 'Caleb Johannsen',
    avatarUrl: cdnUrl(seedKey('caleb-johannsen', 'profile')),
  },
  profile: {
    displayName: 'Caleb Johannsen',
    slug: 'caleb-johannsen',
    bio: 'Caleb Johannsen is a Scandinavian-American printmaker and woodworker based in Minneapolis, Minnesota. For over twenty-five years, his practice has centered on the intersection of traditional Nordic craft and contemporary fine art printmaking. His lithographs and woodcuts depict the quiet landscapes of the upper Midwest — frozen lakes, birch groves, and prairie horizons — while his furniture and turned objects draw from Scandinavian design principles of simplicity and function. Johannsen holds an MFA from the Minneapolis College of Art and Design and a BFA from St. Olaf College. He has exhibited at the Weisman Art Museum, the American Swedish Institute, and Highpoint Center for Printmaking, where he is a master printer.',
    location: 'Minneapolis, MN',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '55401',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('caleb-johannsen', 'cover')),
    profileImageUrl: cdnUrl(seedKey('caleb-johannsen', 'profile')),
    applicationSource: 'advisor_network',
    isDemo: true,
  },
  categories: ['print', 'woodworking'],
  cvEntries: [
    { type: 'education', title: 'MFA, Printmaking', institution: 'Minneapolis College of Art and Design, MN', year: 1999, sortOrder: 1 },
    { type: 'education', title: 'BFA, Studio Art', institution: 'St. Olaf College, Northfield, MN', year: 1995, sortOrder: 2 },
    { type: 'exhibition', title: 'Northern Light', institution: 'Weisman Art Museum, Minneapolis, MN', year: 2024, sortOrder: 3 },
    { type: 'exhibition', title: 'Craft and Landscape', institution: 'American Swedish Institute, Minneapolis, MN', year: 2022, sortOrder: 4 },
    { type: 'residency', title: 'Master Printer in Residence', institution: 'Highpoint Center for Printmaking, Minneapolis, MN', year: 2015, sortOrder: 5 },
    { type: 'award', title: 'McKnight Artist Fellowship', institution: 'McKnight Foundation, Minneapolis, MN', year: 2020, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Boundary Waters, Winter',
      description: 'Stone lithograph printed from a Bavarian limestone plate at Highpoint Center for Printmaking. The image captures a frozen lake in the Boundary Waters Canoe Area at dawn. Subtle grey tones and fine grain create a quiet, meditative atmosphere. Edition of twenty.',
      medium: 'lithograph on Rives BFK, edition of 20',
      category: 'print',
      price: 12000,
      status: 'available',
      isDocumented: true,
      artworkLength: 18, artworkWidth: 24, artworkHeight: 0,
      packedLength: 22, packedWidth: 28, packedHeight: 3,
      packedWeight: 1.5,
    },
    {
      title: 'Birch Grove',
      description: 'Large-format woodcut of a stand of white birch trees in autumn. The pale trunks are left as the unprinted paper, while the surrounding forest is rendered in warm amber and deep brown. Reduction print from cherry plywood. Edition of fifteen.',
      medium: 'reduction woodcut on cotton rag, edition of 15',
      category: 'print',
      price: 16000,
      status: 'available',
      isDocumented: true,
      artworkLength: 22, artworkWidth: 30, artworkHeight: 0,
      packedLength: 26, packedWidth: 34, packedHeight: 3,
      packedWeight: 2,
    },
    {
      title: 'Turned Bowl, Cherry',
      description: 'Hand-turned bowl from sustainably harvested cherry wood. The simple, rounded form follows Scandinavian design principles. Finished with food-safe walnut oil, revealing the rich grain and warm color of the cherry.',
      medium: 'hand-turned cherry, walnut oil finish',
      category: 'woodworking',
      price: 12000,
      status: 'available',
      isDocumented: false,
      artworkLength: 10, artworkWidth: 10, artworkHeight: 4,
      packedLength: 14, packedWidth: 14, packedHeight: 8,
      packedWeight: 3,
    },
    {
      title: 'Prairie Horizon',
      description: 'Minimalist lithograph depicting a single prairie horizon line. Printed in a warm grey from stone at Highpoint Center. The extreme simplicity of the composition demands precision in printing. Edition of thirty.',
      medium: 'lithograph on Rives BFK, edition of 30',
      category: 'print',
      price: 6500,
      status: 'available',
      isDocumented: false,
      artworkLength: 12, artworkWidth: 18, artworkHeight: 0,
      packedLength: 16, packedWidth: 22, packedHeight: 2,
      packedWeight: 1,
    },
    {
      title: 'Lake Superior, November',
      description: 'Large stone lithograph depicting the North Shore of Lake Superior under heavy November clouds. Printed in three grey-blue tones from separate stones. The most technically ambitious piece in the Northern Light series.',
      medium: 'lithograph on Rives BFK, edition of 12',
      category: 'print',
      price: 18000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 24, artworkWidth: 36, artworkHeight: 0,
      packedLength: 28, packedWidth: 40, packedHeight: 3,
      packedWeight: 2,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('caleb-johannsen', 'process/studio')), sortOrder: 0 },
  ],
}

export const printArtists: ArtistSeedConfig[] = [
  renConfig,
  desireeConfig,
  nathanConfig,
  calebConfig,
]
