import type { ArtistSeedConfig } from '../types'
import { cdnUrl, seedKey } from '../cdn'

// ============================================================================
// Hank Larsen — Bozeman, MT — woodworking, mixed_media — Established (60s)
// ============================================================================

const hankConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-hank-larsen-cognito',
    email: 'hank@hanklarsenwoodwork.com',
    fullName: 'Hank Larsen',
    avatarUrl: cdnUrl(seedKey('hank-larsen', 'profile')),
  },
  profile: {
    displayName: 'Hank Larsen',
    slug: 'hank-larsen',
    bio: 'Hank Larsen is a Norwegian-American woodworker and mixed media artist based in Bozeman, Montana. For over thirty-five years, his practice has centered on hand-joined furniture and sculptural objects made from locally harvested timber — lodgepole pine, cottonwood, and reclaimed barn wood from the Gallatin Valley. His work combines traditional Scandinavian joinery techniques with the rough-hewn aesthetic of the Mountain West, creating pieces that are functional, durable, and deeply connected to place. Larsen studied furniture design at the Center for Furniture Craftsmanship in Rockport, Maine, and holds a BA from Montana State University. His furniture is in the collections of the Yellowstone Art Museum and the Holter Museum of Art.',
    location: 'Bozeman, MT',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '59715',
    status: 'approved',
    commissionsOpen: false,
    coverImageUrl: cdnUrl(seedKey('hank-larsen', 'cover')),
    profileImageUrl: cdnUrl(seedKey('hank-larsen', 'profile')),
    applicationSource: 'advisor_network',
    isDemo: true,
  },
  categories: ['woodworking', 'mixed_media'],
  cvEntries: [
    { type: 'education', title: 'Twelve-Week Intensive', institution: 'Center for Furniture Craftsmanship, Rockport, ME', year: 1992, sortOrder: 1 },
    { type: 'education', title: 'BA, Art', institution: 'Montana State University, Bozeman, MT', year: 1988, sortOrder: 2 },
    { type: 'exhibition', title: 'Timber and Tenon', institution: 'Yellowstone Art Museum, Billings, MT', year: 2024, sortOrder: 3 },
    { type: 'exhibition', title: 'Montana Makers', institution: 'Holter Museum of Art, Helena, MT', year: 2021, sortOrder: 4 },
    { type: 'residency', title: 'Artist in Residence', institution: 'Anderson Ranch Arts Center, Snowmass Village, CO', year: 2010, sortOrder: 5 },
    { type: 'award', title: 'Montana Arts Council Individual Artist Fellowship', institution: 'Helena, MT', year: 2019, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Gallatin Bench',
      description: 'Entryway bench made from reclaimed Douglas fir barn beams salvaged from a nineteenth-century homestead in the Gallatin Valley. Hand-cut mortise and tenon joinery, no metal fasteners. The weathered surface of the original beams is preserved on the seat, while the legs are planed smooth. Finished with tung oil.',
      medium: 'reclaimed Douglas fir, hand-joined',
      category: 'woodworking',
      price: 55000,
      status: 'available',
      isDocumented: true,
      artworkLength: 48, artworkWidth: 14, artworkHeight: 18,
      packedLength: 52, packedWidth: 18, packedHeight: 22,
      packedWeight: 35,
    },
    {
      title: 'Turned Bowl, Cottonwood Burl',
      description: 'Large hand-turned bowl from a cottonwood burl harvested along the Gallatin River. The natural edge of the burl is preserved on the rim, creating an organic, irregular form. The spalted figure of the wood reveals dramatic color variations. Finished with walnut oil.',
      medium: 'hand-turned cottonwood burl, walnut oil finish',
      category: 'woodworking',
      price: 28000,
      status: 'available',
      isDocumented: true,
      artworkLength: 14, artworkWidth: 14, artworkHeight: 6,
      packedLength: 18, packedWidth: 18, packedHeight: 10,
      packedWeight: 5,
    },
    {
      title: 'Cutting Board, End Grain',
      description: 'End-grain cutting board made from locally harvested hard maple. The checkerboard pattern of end-grain construction is both visually striking and functionally superior for knife maintenance. Finished with food-safe mineral oil and beeswax.',
      medium: 'hard maple, mineral oil and beeswax finish',
      category: 'woodworking',
      price: 12000,
      status: 'available',
      isDocumented: false,
      artworkLength: 18, artworkWidth: 12, artworkHeight: 2,
      packedLength: 22, packedWidth: 16, packedHeight: 6,
      packedWeight: 8,
    },
    {
      title: 'Wall Shelf, Lodge Pole',
      description: 'Floating wall shelf made from a single slab of lodgepole pine with live edge. The bark edge is stabilized with clear epoxy to preserve the natural form. Hand-cut dovetail wall bracket hidden behind the shelf. Finished with tung oil.',
      medium: 'lodgepole pine, tung oil finish',
      category: 'woodworking',
      price: 18000,
      status: 'available',
      isDocumented: false,
      artworkLength: 36, artworkWidth: 8, artworkHeight: 2,
      packedLength: 40, packedWidth: 12, packedHeight: 6,
      packedWeight: 8,
    },
    {
      title: 'Writing Desk, Reclaimed Fir',
      description: 'Compact writing desk made from reclaimed Douglas fir with hand-cut dovetail drawers in maple. The desk design references Scandinavian mid-century forms adapted for a mountain cabin. The warm patina of the old-growth fir develops further over time.',
      medium: 'reclaimed Douglas fir, maple',
      category: 'woodworking',
      price: 55000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 42, artworkWidth: 24, artworkHeight: 30,
      packedLength: 46, packedWidth: 28, packedHeight: 34,
      packedWeight: 45,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('hank-larsen', 'process/studio')), sortOrder: 0 },
  ],
}

// ============================================================================
// Marcus Whitfield — Richmond, VA — woodworking, ceramics — Mid-career (40s)
// ============================================================================

const marcusConfig: ArtistSeedConfig = {
  user: {
    cognitoId: 'seed-marcus-whitfield-cognito',
    email: 'marcus@marcuswhitfieldstudio.com',
    fullName: 'Marcus Whitfield',
    avatarUrl: cdnUrl(seedKey('marcus-whitfield', 'profile')),
  },
  profile: {
    displayName: 'Marcus Whitfield',
    slug: 'marcus-whitfield',
    bio: 'Marcus Whitfield is an African-American woodworker and ceramicist based in Richmond, Virginia. His practice bridges the woodworking traditions of the Chesapeake Bay region with his own exploration of Black material culture. Whitfield creates turned vessels, carved utensils, and functional pottery that honor the handcraft traditions of the enslaved artisans who built much of Virginia\'s material heritage. He holds an MFA from Virginia Commonwealth University and a BFA from Hampton University. He has exhibited at the Virginia Museum of Fine Arts, the Renwick Gallery, and the National Museum of African American History and Culture. He teaches woodworking at the Visual Arts Center of Richmond.',
    location: 'Richmond, VA',
    websiteUrl: null,
    instagramUrl: null,
    originZip: '23220',
    status: 'approved',
    commissionsOpen: true,
    coverImageUrl: cdnUrl(seedKey('marcus-whitfield', 'cover')),
    profileImageUrl: cdnUrl(seedKey('marcus-whitfield', 'profile')),
    applicationSource: 'advisor_network',
    isDemo: true,
  },
  categories: ['woodworking', 'ceramics'],
  cvEntries: [
    { type: 'education', title: 'MFA, Craft/Material Studies', institution: 'Virginia Commonwealth University, Richmond, VA', year: 2012, sortOrder: 1 },
    { type: 'education', title: 'BFA, Fine Arts', institution: 'Hampton University, Hampton, VA', year: 2008, sortOrder: 2 },
    { type: 'exhibition', title: 'Material Witness', institution: 'Virginia Museum of Fine Arts, Richmond, VA', year: 2025, sortOrder: 3 },
    { type: 'exhibition', title: 'Making and Meaning', institution: 'Renwick Gallery, Smithsonian, Washington, DC', year: 2022, sortOrder: 4 },
    { type: 'residency', title: 'Artist in Residence', institution: 'Center for Furniture Craftsmanship, Rockport, ME', year: 2018, sortOrder: 5 },
    { type: 'award', title: 'Virginia Museum of Fine Arts Fellowship', institution: 'Richmond, VA', year: 2023, sortOrder: 6 },
  ],
  listings: [
    {
      title: 'Turned Vessel, Black Walnut',
      description: 'Large hand-turned vessel from a Virginia black walnut tree felled by Hurricane Ian. The dramatic figure of the wood — swirling grain and rich chocolate color — is revealed through careful turning and a hand-rubbed oil finish. The vessel form references both African and Chesapeake Bay pottery traditions.',
      medium: 'hand-turned black walnut, oil finish',
      category: 'woodworking',
      price: 32000,
      status: 'available',
      isDocumented: true,
      artworkLength: 10, artworkWidth: 10, artworkHeight: 8,
      packedLength: 14, packedWidth: 14, packedHeight: 12,
      packedWeight: 5,
    },
    {
      title: 'Serving Spoons, Cherry',
      description: 'Pair of hand-carved serving spoons in cherry wood. The bowls are deeply scooped using traditional hook knives, and the handles are carved with a subtle faceted texture. Finished with food-safe walnut oil. Each spoon is slightly different, reflecting the hand-carving process.',
      medium: 'hand-carved cherry, walnut oil finish',
      category: 'woodworking',
      price: 8500,
      status: 'available',
      isDocumented: false,
      artworkLength: 12, artworkWidth: 3, artworkHeight: 1.5,
      packedLength: 16, packedWidth: 7, packedHeight: 5.5,
      packedWeight: 1,
    },
    {
      title: 'Stoneware Pitcher, iron glaze',
      description: 'Hand-thrown stoneware pitcher with a rich iron-saturated glaze. The form references historical stoneware produced by enslaved potters in Edgefield, South Carolina. A pouring lip and pulled handle make this a fully functional piece. Dishwasher and microwave safe.',
      medium: 'stoneware, iron glaze',
      category: 'ceramics',
      price: 12000,
      status: 'available',
      isDocumented: true,
      artworkLength: 6, artworkWidth: 5, artworkHeight: 9,
      packedLength: 10, packedWidth: 9, packedHeight: 13,
      packedWeight: 4,
    },
    {
      title: 'Cheese Board, Reclaimed Oak',
      description: 'Serving board made from reclaimed white oak salvaged from a tobacco barn in Halifax County, Virginia. The old-growth oak has a tight, dense grain and a warm amber color that darkens with age. Finished with food-safe mineral oil.',
      medium: 'reclaimed white oak, mineral oil finish',
      category: 'woodworking',
      price: 9500,
      status: 'available',
      isDocumented: false,
      artworkLength: 16, artworkWidth: 8, artworkHeight: 1,
      packedLength: 20, packedWidth: 12, packedHeight: 5,
      packedWeight: 4,
    },
    {
      title: 'Ceremonial Bowl, Ash',
      description: 'Large hand-turned ceremonial bowl in white ash. The wide, shallow form is inspired by African libation bowls used in communal gatherings. The exterior is carved with a subtle ribbed texture while the interior is polished smooth. Not intended for food use.',
      medium: 'hand-turned white ash, oil finish',
      category: 'woodworking',
      price: 38000,
      status: 'sold',
      isDocumented: true,
      artworkLength: 16, artworkWidth: 16, artworkHeight: 5,
      packedLength: 20, packedWidth: 20, packedHeight: 9,
      packedWeight: 6,
    },
  ],
  processMedia: [
    { type: 'photo', url: cdnUrl(seedKey('marcus-whitfield', 'process/studio')), sortOrder: 0 },
  ],
}

export const woodworkingArtists: ArtistSeedConfig[] = [
  hankConfig,
  marcusConfig,
]
